export type EnhancementMode = "new" | "existing" | "covered";

export type EnhancementItem = {
  id: string;
  title: string;
  batch: string;
  area: string;
  href: string;
  mode: EnhancementMode;
};

export type EnhancementBatch = {
  id: string;
  title: string;
  deck: string;
  href: string;
  area: string;
  mode: EnhancementMode;
  items: EnhancementItem[];
};

type BatchInput = Omit<EnhancementBatch, "items"> & { items: string[] };

function makeBatch(input: BatchInput): EnhancementBatch {
  return {
    ...input,
    items: input.items.map((title, index) => ({
      id: `${input.id}-${String(index + 1).padStart(2, "0")}`,
      title,
      batch: input.title,
      area: input.area,
      href: input.href,
      mode: input.mode,
    })),
  };
}

export const excludedEnhancements = [
  "Arabic language features, Arabic search, RTL layouts and Arabic/Tunisian localisation are excluded by request.",
  "Tunisia-specific SEO/localisation additions are excluded by request.",
  "Payment additions are excluded by request: card integrations, wallets, bank-transfer proof upload, split-payment placeholders, saved cards, checkout point redemption, and gift-card purchase/redemption flows.",
];

export const enhancementBatches: EnhancementBatch[] = [
  makeBatch({
    id: "storefront",
    title: "Batch 01 — Storefront collections",
    deck: "Collection shelves, budgets, seasonal edits, best sellers, new arrivals and back-in-stock discovery.",
    href: "/collections",
    area: "Storefront",
    mode: "new",
    items: [
      "Shop by concern landing experience",
      "Shop by skin type discovery",
      "Shop by routine step discovery",
      "Visual routine builder entry point",
      "Skin and hair quiz entry point",
      "Recommendation result page after quiz",
      "Product comparison entry point",
      "Best sellers this week shelf",
      "New arrivals shelf",
      "Pharmacist choice shelf",
      "Budget shelves under 30, 50 and 100 DT",
      "French pharmacy favourites collection",
      "Warm-climate essentials collection",
      "Summer essentials collection",
      "Winter barrier repair collection",
      "Pregnancy-safe picks collection",
      "Teen acne starter kit collection",
      "Men grooming collection",
      "Travel-size essentials collection",
      "Back-in-stock collection",
    ],
  }),
  makeBatch({
    id: "search",
    title: "Batch 02 — Product discovery and search",
    deck: "Smarter search, filters, saved discovery paths and zero-result recovery without adding Arabic/Tunisian search variants.",
    href: "/recherche",
    area: "Search",
    mode: "existing",
    items: [
      "Instant search suggestions",
      "Typo-tolerant search",
      "Brand autocomplete",
      "Ingredient autocomplete",
      "Concern autocomplete",
      "Search history for signed-in customers",
      "Trending searches",
      "No-result smart suggestions",
      "Synonym matching such as boutons to acne and ecran to sunscreen",
      "Barcode search entry point",
      "Voice-search ready UX",
      "Price range filter",
      "Discount filter",
      "Stock availability filter",
      "Rating filter",
      "Age suitability filter",
      "Fragrance-free filter",
      "Pregnancy and breastfeeding suitability filter",
      "Sensitive-skin approved filter",
      "Recent searches recovery",
    ],
  }),
  makeBatch({
    id: "pdp",
    title: "Batch 03 — Product page intelligence",
    deck: "Every product becomes an advice sheet: ingredients, warnings, texture, routine order, lots and review intelligence.",
    href: "/boutique",
    area: "Product pages",
    mode: "existing",
    items: [
      "Ingredient explanation blocks",
      "Why we recommend it pharmacist note",
      "Who should avoid this warnings",
      "Before and after usage timeline",
      "Texture labels",
      "Finish labels such as matte, glowy, invisible and rich",
      "Usage frequency guidance",
      "Layering order guidance",
      "Pairs well with section",
      "Do not combine with section",
      "Routine compatibility score",
      "Allergy warning badges",
      "Comedogenic-risk indicator",
      "pH level field where relevant",
      "PAO and expiry visibility",
      "Batch and lot freshness info",
      "Product video preview slots",
      "Customer photo review slots",
      "Verified purchase badge on reviews",
      "Review filters by skin type, age and concern",
    ],
  }),
  makeBatch({
    id: "cart",
    title: "Batch 04 — Cart and checkout without payment additions",
    deck: "Checkout confidence, delivery clarity, gifts, pickup and recovery while leaving payment systems untouched.",
    href: "/panier",
    area: "Cart / checkout",
    mode: "covered",
    items: [
      "Free-shipping progress bar",
      "Cart upsells to complete the routine",
      "Mini-cart recommendations",
      "Gift wrapping option",
      "Handwritten note option",
      "Delivery time estimator by city",
      "Pickup from store option with time slots",
      "Scheduled delivery request",
      "Express delivery toggle",
      "Cart reservation timer for low-stock items",
      "Abandoned-cart email recovery plan",
      "Abandoned-cart SMS or WhatsApp recovery plan",
      "Checkout address validation",
      "Guest checkout path",
      "Automatic promo application",
      "Promo-code suggestions",
      "Bundle discounts",
      "Buy-one-get-one campaign support",
      "Quantity discount pricing",
      "Birthday discount campaign support",
    ],
  }),
  makeBatch({
    id: "account",
    title: "Batch 05 — Customer account and retention",
    deck: "A customer home: orders, routines, profiles, alerts, returns, replenishment and subscriptions.",
    href: "/compte",
    area: "Account",
    mode: "existing",
    items: [
      "Full customer dashboard",
      "Reorder from previous order",
      "Saved routines",
      "Saved skin profile",
      "Saved baby profile",
      "Saved hair profile",
      "Saved addresses with delivery notes",
      "Wishlist price-drop alerts",
      "Wishlist back-in-stock alerts",
      "Order tracking timeline",
      "Invoice download",
      "Return request flow with photos",
      "Cancellation request flow",
      "Subscription management",
      "Product replenishment reminders",
      "Notification centre",
      "Preference centre",
      "Data export request",
      "Account deletion request path",
      "Consent and email opt-in controls",
    ],
  }),
  makeBatch({
    id: "club",
    title: "Batch 06 — Loyalty and community",
    deck: "A Cléopâtre Club layer for points, tiers, referrals, challenges, public lists and community proof.",
    href: "/programme-club",
    area: "Loyalty / community",
    mode: "new",
    items: [
      "Loyalty tiers Bronze, Silver, Gold and VIP",
      "Points history",
      "Points for reviews",
      "Points for referrals",
      "Points for completing profile",
      "Birthday rewards",
      "VIP early access to offers",
      "Community Q&A on product pages",
      "Customer routine sharing",
      "Public wishlists",
      "Cléopâtre Club landing page",
      "Referral dashboard",
      "Badges for loyal customers",
      "Monthly beauty challenge",
      "Customer content gallery",
      "Routine sharing prompts",
      "Review contribution missions",
      "Member-only editorial calendar",
      "Community safety rules",
      "VIP experience timeline",
    ],
  }),
  makeBatch({
    id: "advice",
    title: "Batch 07 — Support and pharmacy advice",
    deck: "Advice, triage, chat, attachments, appointments, FAQ automation and support operations.",
    href: "/conseil-pharmacien",
    area: "Support",
    mode: "new",
    items: [
      "Live chat widget",
      "WhatsApp support button",
      "Ask a pharmacist form",
      "Triage form before support ticket creation",
      "Support ticket attachments",
      "Support ticket satisfaction rating",
      "Product advice booking slots",
      "Video consultation request",
      "Post-purchase care messages",
      "Automated FAQ answers",
      "Escalation tags in admin support",
      "Saved support macros",
      "Internal support notes",
      "Order-linked support conversations",
      "Support presence and typing state",
      "Support read receipts",
      "Conversation assignment",
      "Support metrics endpoint",
      "Attachment download route",
      "Support satisfaction follow-up",
    ],
  }),
  makeBatch({
    id: "admin",
    title: "Batch 08 — Admin and back office",
    deck: "Analytics, inventory, operations, bulk actions, staff controls and product-quality command rooms.",
    href: "/admin/opportunites",
    area: "Admin",
    mode: "existing",
    items: [
      "Admin analytics dashboard",
      "Revenue charts",
      "Product performance reports",
      "Low-stock dashboard",
      "Near-expiry stock dashboard",
      "Margin tracking model",
      "Supplier management workspace",
      "Purchase order management workspace",
      "Stock transfer between stores",
      "Inventory adjustment approvals",
      "Barcode scanner admin mode",
      "Bulk product import",
      "Bulk image upload",
      "Bulk price update",
      "Bulk discount campaign creation",
      "Product content quality score",
      "Missing-photo detection",
      "Expired product auto-alerts",
      "Staff roles and permissions",
      "Admin activity audit timeline",
    ],
  }),
  makeBatch({
    id: "ops",
    title: "Batch 09 — Operations and delivery",
    deck: "Delivery rules, courier workflow, packing, pickup, failed delivery handling and operations alerts.",
    href: "/admin/commandes",
    area: "Operations",
    mode: "covered",
    items: [
      "Delivery zones by service area",
      "Delivery fee rules by city",
      "Courier assignment",
      "Delivery status updates",
      "Packing slips",
      "Pick-pack-ship workflow",
      "Order priority queue",
      "Failed delivery handling",
      "Partial shipment handling",
      "Pickup-ready notifications",
      "Delivery proof upload slot",
      "Driver notes",
      "Store opening hours",
      "Holiday schedule",
      "Operational alerts dashboard",
      "Order problem workflow",
      "Returns operations workspace",
      "Inventory lot labels",
      "Expiry-date clearance workflow",
      "Daily operations digest",
    ],
  }),
  makeBatch({
    id: "marketing",
    title: "Batch 10 — Marketing, content and SEO",
    deck: "Editorial, campaign pages, feeds, structured data, social cards and acquisition analytics without payment or Tunisia-specific SEO additions.",
    href: "/journal",
    area: "Marketing / SEO",
    mode: "covered",
    items: [
      "Blog and articles homepage",
      "Editorial buying guides",
      "Seasonal campaign pages",
      "Brand story pages",
      "Ingredient encyclopedia",
      "Skincare glossary",
      "Newsletter signup incentives",
      "Newsletter segmentation",
      "SMS campaign manager plan",
      "Push notification system",
      "Landing pages for ads",
      "Influencer campaign tracking links",
      "UTM campaign reporting",
      "SEO metadata editor in admin",
      "Automatic sitemap improvements",
      "Structured data for products",
      "Structured data for reviews",
      "Structured data for FAQs",
      "Canonical URL management",
      "Open Graph image generator plan",
    ],
  }),
  makeBatch({
    id: "ux-access",
    title: "Batch 11 — UX, performance and accessibility",
    deck: "Mobile polish, micro-interactions, admin ergonomics, high contrast, larger text and reduced-motion controls.",
    href: "/accessibilite",
    area: "UX / accessibility",
    mode: "new",
    items: [
      "Skeleton loaders",
      "Smoother page transitions",
      "Mobile bottom navigation",
      "Sticky add-to-cart on mobile",
      "Quick-add from product cards",
      "Quick-view product modal plan",
      "Better empty states",
      "Micro-interactions on cart actions",
      "Progress animations during checkout",
      "Recently viewed products",
      "Keyboard shortcuts in admin",
      "Dark admin theme plan",
      "Compact admin table view",
      "Product card hover video slots",
      "Premium loading screen for cinematic homepage",
      "Larger text mode",
      "High-contrast mode",
      "Reduced-motion improvements",
      "Screen-reader review pass",
      "Keyboard navigation audit",
    ],
  }),
  makeBatch({
    id: "trust",
    title: "Batch 12 — Trust, privacy and safety",
    deck: "Consent, privacy controls, safety warnings, recalls and medical disclaimers.",
    href: "/confidentialite",
    area: "Trust / compliance",
    mode: "covered",
    items: [
      "Cookie consent banner plan",
      "Privacy preferences centre",
      "Terms acceptance tracking",
      "GDPR-style data export",
      "Account deletion request",
      "Consent log for marketing emails",
      "Medical disclaimer blocks",
      "Age warnings for specific products",
      "Pregnancy and breastfeeding warning system",
      "Safety recall notice system",
      "Security email notifications",
      "Audit log coverage",
      "Data minimisation copy",
      "Public policy pages",
      "Support privacy language",
      "Customer data rights page",
      "Cookie retention details",
      "Recall banner acknowledgement",
      "Product safety archive",
      "Privacy request SLA",
    ],
  }),
];

export const enhancementItems = enhancementBatches.flatMap((batch) => batch.items);

export const enhancementStats = {
  batches: enhancementBatches.length,
  items: enhancementItems.length,
  newItems: enhancementItems.filter((item) => item.mode === "new").length,
  existingItems: enhancementItems.filter((item) => item.mode === "existing").length,
  coveredItems: enhancementItems.filter((item) => item.mode === "covered").length,
};
