/**
 * LES FICHES, ÉCRITES UNE PAR UNE — solaire, bébé & maman, compléments, hygiène.
 * Mêmes règles : aucune phrase recyclée, composition vérifiée seulement quand
 * elle l'est, et pour les compléments le strict nécessaire — on ne conseille
 * pas une gélule comme on conseille une crème.
 */
import type { Detail } from "./catalogue-details-visage";

export const RESTE: Record<string, Detail> = {
  "Anthelios UVMune 400 Fluide Invisible SPF50+": {
    desc: "Un fluide invisible qui filtre jusqu'aux UVA longs, ceux qui passent les vitres et les nuages, avec la texture la plus légère de la gamme. Il ne laisse ni blanc ni brillance, et se met sous le maquillage.",
    inci: "Aqua, Alcohol Denat., Silica, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Ethylhexyl Salicylate, Butyl Methoxydibenzoylmethane, Glycerin, Tocopherol, Phenoxyethanol, Parfum",
    use: "Appliquer une noisette sur le visage 15 minutes avant de sortir, renouveler toutes les deux heures au soleil.",
    when: "Chaque matin, toute l'année",
    amt: "Une noisette — deux si vous êtes en mer",
    order: "Après la crème, avant le maquillage",
    texture: "Fluide invisible",
    forWhom: "Toutes peaux, hyperpigmentation, anti-âge quotidien",
    precautions: "En quantité insuffisante, aucun SPF 50 ne vaut 50 : la moitié d'une noisette divise la protection par deux.",
    trust: 1,
  },
  "Fotoprotector Fusion Water SPF50": {
    desc: "Une eau de protection à phase aqueuse, la plus fine possible, qui pénètre en dix secondes et laisse la peau mate. C'est le solaire que même ceux qui détestent le solaire finissent par mettre.",
    inci: "Aqua, Ethylhexyl Methoxycinnamate, Alcohol Denat., Glycerin, Silica, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Tocopheryl Acetate, Phenoxyethanol, Parfum",
    use: "Appliquer sur peau humide ou sèche, en tapotant, sans masser.",
    when: "Chaque matin et après chaque baignade",
    amt: "Un doigt de produit pour le visage",
    order: "Dernier geste avant la sortie",
    texture: "Eau ultra-légère",
    forWhom: "Peaux mixtes à grasses, sport, plage",
    precautions: "Très fluide : éviter le contour des yeux et ne pas vaporiser directement sur le visage.",
  },
  "Photoderm Nude Touch SPF50+": {
    desc: "Un solaire teinté matifiant qui couvre les rougeurs et les marques pendant qu'il protège, avec une teinte unique qui s'adapte à la plupart des carnations claires. Il remplace le fond de teint l'été.",
    inci: "Aqua, Dicaprylyl Carbonate, Glycerin, Titanium Dioxide, Iron Oxides, Ethylhexyl Salicylate, Silica, Tocopherol, Phenoxyethanol, Parfum",
    use: "Étaler une noisette du centre vers l'extérieur, en couche régulière, puis compléter au besoin.",
    when: "Chaque matin au soleil",
    amt: "Une noisette",
    order: "Après la crème, à la place du fond de teint",
    texture: "Fluide teinté matifiant",
    forWhom: "Peaux mixtes à grasses, carnations claires, envie de couvrance",
    precautions: "Une seule teinte ne convient pas à toutes les carnations : en boutique, on essaie avant d'acheter.",
  },
  "Capital Soleil UV-Age Daily SPF50+": {
    desc: "Un soin solaire quotidien qui protège et corrige en même temps, avec des actifs anti-âge et un filtre large spectre. Pensé pour la ville : il se fond dans la routine plutôt que de s'y ajouter.",
    inci: "Aqua, Glycerin, Alcohol Denat., Ethylhexyl Salicylate, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Niacinamide, Tocopherol, Sodium Hyaluronate, Phenoxyethanol, Parfum",
    use: "Appliquer le matin en dernier geste de la routine, sur visage et cou.",
    when: "Chaque matin",
    amt: "Une noisette",
    order: "Après le sérum, en dernier",
    texture: "Fluide soin quotidien",
    forWhom: "Toutes peaux, prévention des taches et des rides, ville",
    precautions: "Le nom « daily » est exact : une application le matin de départ en vacances ne protège pas l'après-midi.",
  },
  "Vinosun Crème Protectrice SPF50": {
    desc: "Une crème solaire de visage à base d'antioxydants de vigne, qui protège et nourrit sans laisser de film blanc. Texture crème, donc plus confortable pour les peaux sèches que les fluides.",
    inci: "Aqua, Glycerin, Ethylhexyl Salicylate, Vitis Vinifera Seed Extract, Butyrospermum Parkii Butter, Tocopherol, Sodium Hyaluronate, Phenoxyethanol, Parfum",
    use: "Appliquer généreusement sur visage et cou, renouveler toutes les deux heures d'exposition.",
    when: "Chaque sortie au soleil",
    amt: "Une noisette et demie",
    order: "Après le sérum",
    texture: "Crème solaire nourrissante",
    forWhom: "Peaux normales à sèches, plage et jardin",
    precautions: "Une crème riche peut faire briller en fin de journée sur une peau mixte : préférer alors un fluide.",
  },
  "Anthelios Lait Hydratant SPF50+": {
    desc: "Un lait solaire hydratant pour le corps, qui s'étale vite sur une grande surface et résiste à la baignade. La contenance de 250 ml est pensée pour une famille, pas pour un seul été.",
    inci: "Aqua, Glycerin, Ethylhexyl Salicylate, Dimethicone, Butyl Methoxydibenzoylmethane, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Tocopherol, Phenoxyethanol, Parfum",
    use: "Appliquer une noix généreuse sur le corps 15 minutes avant l'exposition, renouveler après chaque bain.",
    when: "Chaque exposition, toutes les deux heures",
    amt: "Une noix par bras, deux par jambe",
    order: "Avant de s'habiller, sur peau sèche",
    texture: "Lait hydratant",
    forWhom: "Corps, adultes, familles, plage et piscine",
    precautions: "Un tee-shirt mouillé protège moins qu'une crème : la protection vestimentaire n'est pas une protection solaire.",
    trust: 1,
  },
  "Fluide Minéral Corps SPF50+": {
    desc: "Un solaire 100 % minéral à base d'oxyde de zinc, pour les peaux qui réagissent aux filtres chimiques et les femmes enceintes qui préfèrent éviter les filtres organiques. Il laisse un voile blanc assumé.",
    inci: "Aqua, Zinc Oxide, Caprylic/Capric Triglyceride, Glycerin, Silica, Tocopherol, Sodium Hyaluronate, Phenoxyethanol",
    use: "Appliquer généreusement, en couche visible et régulière, renouveler toutes les deux heures.",
    when: "Chaque exposition",
    amt: "Une noix par zone",
    order: "Sur peau sèche, avant de s'habiller",
    texture: "Fluide minéral épais",
    forWhom: "Peaux intolérantes aux filtres chimiques, grossesse, enfants",
    precautions: "Le voile blanc est le signe qu'il y en a assez : en mettre moins revient à ne pas se protéger.",
  },
  "Photoderm Spray SPF50+": {
    desc: "Un spray solaire transparent, pratique pour les épaules et le dos d'un enfant qui bouge. Il s'étale aussi bien que le lait mais arrive plus vite sur les zones difficiles à atteindre.",
    inci: "Aqua, Alcohol Denat., Ethylhexyl Salicylate, Glycerin, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Tocopherol, Phenoxyethanol, Parfum",
    use: "Vaporiser à 20 cm puis étaler avec la main — la pulvérisation seule laisse des zones blanches.",
    when: "Chaque exposition, toutes les deux heures",
    amt: "Trois à quatre vaporisations par zone",
    order: "Avant de partir, puis après la baignade",
    texture: "Spray transparent",
    forWhom: "Corps, zones difficiles d'accès, familles",
    precautions: "Ne jamais vaporiser directement sur le visage : poser d'abord dans la main, puis étaler.",
  },
  "Posthelios Gel-Crème Après-Soleil": {
    desc: "Un gel-crème après-soleil qui refroidit la peau échauffée et prolonge le bronzage, à mettre dans le réfrigérateur pendant les vacances. Il apaise, il ne remplace pas un traitement de coup de soleil.",
    inci: "Aqua, Glycerin, Alcohol Denat., Butyrospermum Parkii Butter, Allantoin, Tocopherol, Sodium Hyaluronate, Carbomer, Phenoxyethanol, Parfum",
    use: "Appliquer en couche épaisse le soir sur les zones exposées, sans frotter.",
    when: "Après chaque exposition",
    amt: "Une noix par zone",
    order: "Après la douche du soir",
    texture: "Gel-crème frais",
    forWhom: "Peaux échauffées, coups de soleil légers, fin de journée de plage",
    precautions: "Sur un coup de soleil avec cloques ou fièvre, ce n'est plus une crème : consultez le jour même.",
  },
  "Lait Après-Soleil Réparateur": {
    desc: "Un lait après-soleil nourrissant qui répare la barrière abîmée par le sel et le chlore, avec du panthénol. Il s'adresse aux peaux qui pèlent et tirent après trois jours de mer.",
    inci: "Aqua, Glycerin, Paraffinum Liquidum, Panthenol, Butyrospermum Parkii Butter, Tocopherol, Xanthan Gum, Phenoxyethanol, Parfum",
    use: "Appliquer généreusement après la douche du soir, en insistant sur les épaules et le dos.",
    when: "Chaque soir d'exposition",
    amt: "Une noix par zone",
    order: "Sur peau propre, en dernier geste",
    texture: "Lait réparateur",
    forWhom: "Peaux sèches après le soleil, suites de baignades",
    precautions: "Ni ce lait ni aucun autre ne raccourcit un coup de soleil : il soulage, c'est tout, et c'est déjà beaucoup.",
  },
  "Anthelios Dermo-Pediatrics Lait SPF50+": {
    desc: "Un lait solaire pour enfants testé sous contrôle pédiatrique, sans parfum et sans alcool, qui résiste à l'eau et au sable. Il s'étale sur une peau de bébé sans laisser de traces blanches épaisses.",
    inci: "Aqua, Glycerin, Dimethicone, Ethylhexyl Salicylate, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Tocopherol, Sodium Hyaluronate, Phenoxyethanol",
    use: "Appliquer une noix généreuse avant la sortie, renouveler toutes les deux heures et après chaque bain.",
    when: "Chaque exposition",
    amt: "Une noix par zone découverte",
    order: "À la maison, avant de s'habiller",
    texture: "Lait enfant",
    forWhom: "Enfants dès 3 mois, peaux délicates",
    precautions: "Le sable et le vent augmentent la dose reçue : en bord de mer, renouveler plutôt toutes les heures et demie.",
    ageMin: 6,
  },
  "Pediatrics Fusion Water SPF50": {
    desc: "Une eau solaire enfant, ultra-légère et sans parfum, pour les enfants qui refusent « la crème qui colle ». Elle se met en dix secondes et donc, en pratique, elle se met tout court.",
    inci: "Aqua, Ethylhexyl Methoxycinnamate, Alcohol Denat., Glycerin, Silica, Tocopheryl Acetate, Phenoxyethanol",
    use: "Appliquer sur peau humide ou sèche, en tapotant visage, oreilles et nuque, puis étaler sur les bras.",
    when: "Chaque exposition",
    amt: "Un doigt de produit par zone",
    order: "À la maison, avant la piscine",
    texture: "Eau légère enfant",
    forWhom: "Enfants dès 4 ans, sport, piscine",
    precautions: "Contient de l'alcool : à éviter sur une peau très sèche ou lésée, préférer alors le lait enfant.",
    ageMin: 48,
  },
  "Gel Lavant Doux": {
    desc: "Un gel lavant sans savon, à la glycérine et au panthénol, pour le corps et les cheveux d'un bébé, sans piquer les yeux. Il laisse la peau souple et évite la sécheresse des bains quotidiens.",
    inci: "Aqua, Glycerin, Coco-Glucoside, Sodium Cocoyl Glutamate, Panthenol, Citric Acid, Sodium Benzoate, Parfum",
    use: "Verser une noisette dans la main ou dans l'eau du bain, laver, rincer.",
    when: "À chaque bain",
    amt: "Une noisette — deux pour le bain complet",
    order: "Corps d'abord, cheveux ensuite",
    texture: "Gel lavant sans savon",
    forWhom: "Nourrissons et enfants, peaux délicates",
    precautions: "La température du bain se mesure au coude, pas à la main : 36 à 37 °C.",
    ageMin: 0,
  },
  "Eau Nettoyante Sans Rinçage": {
    desc: "Une eau de nettoyage qui se pose au coton et s'en va sans rinçage, pour les changes de nuit et les sorties de maternité. Elle respecte le film de la peau du nouveau-né.",
    inci: "Aqua, Glycerin, Coco-Glucoside, Panthenol, Citric Acid, Sodium Benzoate",
    use: "Imbiber un coton, passer sur le visage, les plis et le siège, puis sécher en tapotant.",
    when: "À chaque change et le matin",
    amt: "Un coton par zone",
    order: "Avant la crème de change",
    texture: "Eau nettoyante",
    forWhom: "Nouveau-nés, visage et corps, déplacements",
    precautions: "Sans rinçage ne veut pas dire sans nettoyage : sur une peau qui a des résidus, préférer l'eau et le gel lavant.",
    ageMin: 0,
  },
  "ABCDerm Moussant": {
    desc: "Un gel moussant deux-en-un pour le corps et les cheveux, conçu pour un enfant qui se lave seul et qui laisse couler. La formule courte limite les risques de réaction sur les peaux atopiques.",
    inci: "Aqua, Glycerin, Coco-Glucoside, Sodium Cocoyl Glutamate, Panthenol, Citric Acid, Sodium Benzoate",
    use: "Faire mousser sur peau mouillée, laver corps et cheveux, rincer.",
    when: "À chaque bain ou douche",
    amt: "Deux pressions",
    order: "Corps, puis cheveux",
    texture: "Gel moussant enfant",
    forWhom: "Enfants dès 2 ans, peaux atopiques, usage quotidien",
    precautions: "Un enfant ne doit jamais être laissé seul dans la baignoire, quel que soit le produit.",
    ageMin: 24,
  },
  "Crème Change 1-2-3": {
    desc: "Une crème de change barrière qui isole la peau des fesses de l'urine et des selles, avec de l'oxyde de zinc et du panthénol. Elle s'étale sans être épaisse et se nettoie à l'eau tiède.",
    inci: "Aqua, Zinc Oxide, Glycerin, Panthenol, Cetearyl Alcohol, Paraffinum Liquidum, Tocopherol, Phenoxyethanol",
    use: "Appliquer une couche fine à chaque change sur peau propre et sèche, sans frotter les rougeurs.",
    when: "À chaque change",
    amt: "Une noisette",
    order: "Après le nettoyage, avant la couche",
    texture: "Crème barrière",
    forWhom: "Fesses rouges du nourrisson, prévention des irritations",
    precautions: "Si les rougeurs suintent ou s'étendent hors de la couche en dix jours, il s'agit d'une mycose : elle se traite, elle ne se crème pas.",
    ageMin: 0,
  },
  "Cicalfate+ Crème Réparatrice": {
    desc: "Une crème assainissante au cuivre-zinc qui répare l'épiderme abîmé — rougeurs du change, suites de gestes dermatologiques, tatouages récents. Elle crée un milieu qui ne laisse pas les bactéries s'installer.",
    inci: "Aqua, Zinc Oxide, Glycerin, Copper Sulfate, Zinc Sulfate, Cetearyl Alcohol, Panthenol, Tocopherol, Phenoxyethanol",
    use: "Appliquer en couche fine sur la zone, une à deux fois par jour, en débordant d'un centimètre.",
    when: "Matin et soir",
    amt: "Une noisette selon la zone",
    order: "Après le nettoyage, en dernier geste",
    texture: "Crème assainissante",
    forWhom: "Épiderme abîmé, change, tatouages, petites irritations",
    precautions: "Sur une plaie qui ne referme pas en dix jours, consultez.",
    ageMin: 0,
  },
  "Baume Corps Maternité": {
    desc: "Un baume à masser sur le ventre dès le premier mois de grossesse, à la texture riche mais absorbable, pour accompagner l'élasticité de la peau. Il n'efface pas les vergetures, il aide la peau à suivre.",
    inci: "Aqua, Glycerin, Butyrospermum Parkii Butter, Prunus Amygdalus Dulcis Oil, Tocopherol, Panthenol, Xanthan Gum, Phenoxyethanol, Parfum",
    use: "Masser le ventre, les hanches et les cuisses matin et soir, en mouvements circulaires, sans appuyer fort.",
    when: "Matin et soir, dès le premier mois",
    amt: "Une noix par zone",
    order: "Après la douche",
    texture: "Baume de massage",
    forWhom: "Femmes enceintes et allaitantes, peaux qui s'étirent",
    precautions: "Sans aucun actif déconseillé pendant la grossesse : la formule est courte et ne contient ni huile essentielle ni rétinoïde.",
    ageMin: 216,
  },
  "Arkovital Pure Energy": {
    desc: "Des multivitamines 100 % d'origine végétale, avec les vitamines B et C des végétaux, pour les périodes de fatigue et de travail intense. Une cure d'un mois, jamais en continu toute l'année.",
    inci: "Vitamines B1, B2, B3, B5, B6, B8, B9, B12, C — extraits végétaux, comprimé d'origine végétale",
    use: "Un comprimé le matin au petit-déjeuner, avec un verre d'eau.",
    when: "Matin",
    amt: "1 comprimé par jour, cure de 1 mois",
    order: "Au cours du repas",
    texture: "Comprimés",
    forWhom: "Fatigue passagère, récupération, périodes de travail intense",
    precautions: "Une fatigue qui dure plus d'un mois sans raison ne se traite pas par des vitamines : elle s'explique par une prise de sang, sur avis du médecin.",
    ageMin: 180,
  },
  "Vitamine D3 2000 UI": {
    desc: "La vitamine D en dose quotidienne de 2000 UI, le dosage qui compte en Tunisie malgré le soleil : la peau couverte et la crème solaire réduisent la synthèse. Un flacon couvre deux mois.",
    inci: "Vitamine D3 (cholécalciférol) 2000 UI, huile de tournesol, gélule",
    use: "Une capsule par jour avec un repas contenant un peu de gras, pour l'absorption.",
    when: "Matin ou midi",
    amt: "1 capsule par jour",
    order: "Au cours du repas",
    texture: "Capsules huileuses",
    forWhom: "Carence en vitamin D, os, immunité, peu d'exposition au soleil",
    precautions: "Une carence se confirme par un dosage sanguin ; une dose forte ne se prend pas sans bilan, la vitamine D s'accumule.",
    ageMin: 36,
  },
  "Arkogélules Ginseng Bio": {
    desc: "Le ginseng du Panax en gélules titré, pour le tonus physique et intellectuel des périodes de fatigue. C'est un stimulant : il se prend le matin, jamais le soir.",
    inci: "Extrait de racine de ginseng (Panax ginseng) biologique titré en ginsénosides, gélule végétale",
    use: "Une gélule le matin au petit-déjeuner, en cure de trois semaines.",
    when: "Matin",
    amt: "1 gélule par jour",
    order: "Au petit-déjeuner, jamais après 16 h",
    texture: "Gélules de ginseng titré",
    forWhom: "Fatigue intellectuelle, baisse de tonus, cures de rentrée",
    precautions: "Déconseillé en cas d'hypertension non contrôlée, de traitement anticoagulant, ou chez la femme enceinte, et à espacer du café.",
    ageMin: 216,
  },
  "Arkorelax Sommeil Fort 8h": {
    desc: "De la mélatonine à libération prolongée qui accompagne les huit heures d'une nuit, pour s'endormir et surtout ne pas se réveiller à trois heures du matin. Trois semaines de cure, pas plus.",
    inci: "Mélatonine 2 mg à libération prolongée, magnésium marin, extrait d'eschscholtzia, comprimé",
    use: "Un comprimé 30 minutes avant le coucher, avec un verre d'eau.",
    when: "Le soir, 30 minutes avant de dormir",
    amt: "1 comprimé",
    order: "Après le dîner, avant le coucher",
    texture: "Comprimés à libération prolongée",
    forWhom: "Endormissement difficile, réveils nocturnes, décalage horaire",
    precautions: "À ne pas conduire dans les heures qui suivent la prise, et à éviter en cas de traitement psychotrope sans avis médical. Une insomnie de plus d'un mois demande un médecin.",
    ageMin: 216,
  },
  "Arkogélules Magnésium Marin": {
    desc: "Un magnésium marin plus une plante apaisante, pour les crampes, les paupières qui sautent et la fatigue nerveuse de la fin d'été. Il se prend en cure, souvent en alternance avec une autre forme.",
    inci: "Magnésium marin, extrait d'eschscholtzia, gélule végétale",
    use: "Deux gélules le matin et une le soir, avec un verre d'eau.",
    when: "Matin et soir",
    amt: "3 gélules par jour, cure de 1 mois",
    order: "Au cours des repas",
    texture: "Gélules de magnésium marin",
    forWhom: "Crampes, stress, fatigue nerveuse, spasmophilie",
    precautions: "Un magnésium peut donner des selles molles : réduire la dose matin et soir plutôt que d'arrêter.",
    ageMin: 180,
  },
  "Skin Booster Collagène": {
    desc: "Du collagène marin hydrolysé et de l'acide hyaluronique en sticks buvables, pour la peau déshydratée de l'intérieur — une cure à faire à l'automne, quand la peau se dessèche au chauffage.",
    inci: "Collagène marin hydrolysé, acide hyaluronique, vitamine C, zinc, arôme, stick",
    use: "Un stick à boire le matin, à jeun ou au petit-déjeuner, en cure de six semaines.",
    when: "Matin",
    amt: "1 stick par jour",
    order: "Avant le café",
    texture: "Sticks buvables",
    forWhom: "Peau déshydratée, rides qui se creusent, ongles fragiles",
    precautions: "Allergènes marins : à éviter en cas d'allergie aux poissons et crustacés, et la vitamine C contenue doit être signalée si vous en prenez déjà.",
  },
  "Arkogélules Charbon Végétal": {
    desc: "Du charbon végétal activé qui absorbe les gaz et soulage l'inconfort digestif après un repas trop lourd. Il absorbe aussi les médicaments : on l'écarte de deux heures de toute autre prise.",
    inci: "Charbon végétal activé (poudre), gélule végétale d'origine cellulosique, sans additif ni colorant",
    use: "Deux gélules au moment du repas ou dans l'heure qui suit, avec un verre d'eau.",
    when: "Après un repas lourd, ponctuellement",
    amt: "2 gélules par prise, 2 prises maximum par jour",
    order: "À distance de tout autre médicament (2 heures)",
    texture: "Gélules noires",
    forWhom: "Ballonnements, gaz, inconfort digestif ponctuel",
    precautions: "Le charbon piège les médicaments et la pilule contraceptive : respecter deux heures d'écart, et ne pas en faire un usage quotidien.",
    ageMin: 180,
  },
  "Dentifrice Sensibilité": {
    desc: "Un dentifrice qui obture les canaux de la dentine à nu, pour les sensibilités au froid et au sucré. Son effet s'installe après deux semaines d'usage régulier, pas dès le premier brossage.",
    inci: "Aqua, Sorbitol, Hydrated Silica, Glycerin, Potassium Nitrate, Sodium Fluoride 1450 ppm, Xanthan Gum, Sodium Saccharin, Aroma",
    use: "Brosser deux minutes, deux fois par jour, puis recracher sans rincer à l'eau.",
    when: "Matin et soir",
    amt: "Un grain de riz pour un enfant, un petit pois pour un adulte",
    order: "Après les repas, avant le fil",
    texture: "Dentifrice tube",
    forWhom: "Dents sensibles, déchaussement léger, suites de soins",
    precautions: "Une sensibilité qui persiste ou se localise sur une dent demande un dentiste : ce n'est pas toujours l'émail.",
  },
  "Gyn-Phy Gel Intime": {
    desc: "Un gel d'hygiène intime au pH physiologique et à l'acide lactique, sans savon, pour ne pas perturber la flore. C'est un produit de toilette, pas un traitement.",
    inci: "Aqua, Coco-Glucoside, Glycerin, Lactic Acid, Sodium Benzoate, Citric Acid",
    use: "Appliquer en mousse sur les muqueuses externes avec la main, rincer à l'eau tiède.",
    when: "Une fois par jour, ou tous les deux jours",
    amt: "Une noisette",
    order: "Pendant la douche ou le bain",
    texture: "Gel d'hygiène pH 5,5",
    forWhom: "Toilette intime quotidienne, suites d'antibiotiques, grossesse",
    precautions: "En cas de démangeaisons, d'odeur inhabituelle ou de brûlures, aucune toilette ne traite : consultez.",
  },
  "Déodorant 48h Anti-Traces": {
    desc: "Un anti-transpirant au chlorhydrate d'aluminium qui bloque la transpiration à la source et laisse les vêtements intacts. Il s'applique le soir, quand la glande est au repos — c'est là qu'il travaille.",
    inci: "Aqua, Aluminum Chlorohydrate, Glycerin, Dimethicone, Parfum, Tocopheryl Acetate",
    use: "Appliquer sur peau propre et sèche le soir, laisser sécher, se laver le matin.",
    when: "Le soir",
    amt: "Deux passages par aisselle",
    order: "Après la douche du soir, pas après celle du matin",
    texture: "Roll-on anti-traces",
    forWhom: "Transpiration importante, vêtements foncés, été",
    precautions: "À ne pas appliquer sur une peau rasée de frais ni sur une irritation : cela pique et la barrière s'abîme.",
  },
  "Déodorant Roll-on Douceur": {
    desc: "Un déodorant sans sels d'aluminium qui neutralise les odeurs sans bloquer la transpiration, avec une formule courte pour les peaux réactives. Le roll-on se pose le matin, pas la veille.",
    inci: "Aqua, Glycerin, Glycerol, Triethyl Citrate, Sodium Benzoate, Citric Acid",
    use: "Appliquer sur peau propre et sèche en deux passages, laisser sécher avant de s'habiller.",
    when: "Matin",
    amt: "Deux passages par aisselle",
    order: "Après la douche",
    texture: "Roll-on doux",
    forWhom: "Peaux réactives, suites d'épilation, grossesse",
    precautions: "Sans sel d'aluminium, il ne réduit pas la transpiration : si les traces mouillées sont le problème, ce n'est pas le bon produit.",
    trust: 1,
  },
  "Cicaplast Baume B5+": {
    desc: "Un baume réparateur multi-usages qui apaisé les zones irritées — rougeurs, échauffements, suites de gestes — pour toute la famille. Il se tartine sans précaution particulière, bébé compris.",
    inci: "Aqua, Glycerin, Butyrospermum Parkii Butter, Panthenol, Dimethicone, Zinc Gluconate, Madecassoside, Tocopherol, Phenoxyethanol, Parfum",
    use: "Appliquer une couche fine sur la zone irritée, deux fois par jour ; en couche épaisse sur les lèvres gercées.",
    when: "Matin et soir",
    amt: "Une noisette",
    order: "En dernier geste, après tout autre soin",
    texture: "Baume réparateur multi-usages",
    forWhom: "Zones irritées, suites de gestes, toute la famille, bébés",
    precautions: "Contient du parfum : sur une muqueuse ou une plaie ouverte, un soin sans parfum est préférable.",
    trust: 1,
  },
  "Bariéderm Cica Spray": {
    desc: "Un spray assainissant au cuivre-zinc qui se pose sans toucher la peau, pour les zones abîmées qu'on ne veut ni frotter ni masser. Pratique sur les pliures et les suites de gestes techniques.",
    inci: "Aqua, Copper Sulfate, Zinc Sulfate, Glycerin, Panthenol, Sodium Chloride",
    use: "Vaporiser à 10 cm sur la zone propre, laisser sécher à l'air, deux fois par jour.",
    when: "Matin et soir",
    amt: "Une pulvérisation par zone",
    order: "Après le nettoyage, avant une crème si besoin",
    texture: "Spray assainissant sans contact",
    forWhom: "Zones douloureuses au toucher, pliures, suites de soins, enfants",
    precautions: "Ne pas vaporiser directement sur le visage ni dans les plis profonds fermés sans laisser sécher.",
    ageMin: 0,
  },
};
