/**
 * LES FICHES, ÉCRITES UNE PAR UNE — corps & cheveux.
 * Mêmes règles que pour le visage : aucune phrase recyclée, et une composition
 * qui ne se prétend vérifiée que lorsqu'elle l'est (`trust: 1`).
 */
import type { Detail } from "./catalogue-details-visage";

export const CORPS: Record<string, Detail> = {
  "Lipikar Baume AP+M": {
    desc: "Un baume relipidant qui espaces les poussées de sécheresse sévère : la niacinamide et le beurre de karité restaurent la barrière, l'AP+M calme le grattage. Il se tartine sur le corps entier, bébé compris.",
    inci: "Aqua, Butyrospermum Parkii Butter, Glycerin, Dimethicone, Niacinamide, Paraffinum Liquidum, Cetearyl Alcohol, Shea Butter, Ceramide NP, Tocopherol, Phenoxyethanol",
    use: "Appliquer une noix généreuse sur le corps, deux fois par jour pendant les poussées, une fois en entretien.",
    when: "Matin et soir",
    amt: "Une noix par zone",
    order: "Juste après la douche, sur peau encore humide",
    texture: "Baume relipidant riche",
    forWhom: "Peaux très sèches et atopiques, nourrissons à adultes",
    precautions: "Si les lésions suintent ou s'infectent, ce n'est plus une sécheresse : consultez avant de poursuivre.",
    trust: 1,
  },
  "XeraCalm A.D Crème Relipidante": {
    desc: "Une crème anti-démangeaison née d'une souche bactérienne apaisante, pour les peaux atopiques qui se grattent la nuit. Elle agit sur la sensation de démangeaison, ce que les baumes classiques ne font pas.",
    inci: "Aqua, Glycerin, Paraffinum Liquidum, Cetearyl Alcohol, Butyrospermum Parkii Butter, Niacinamide, Aquaphilus Dolomiae Extract, Tocopherol, Xanthan Gum, Phenoxyethanol",
    use: "Appliquer matin et soir sur les zones qui démangent, en massant sans frotter.",
    when: "Matin et soir",
    amt: "Une noix",
    order: "Après la douche ; peut se garder au réfrigérateur l'été",
    texture: "Crème relipidante apaisante",
    forWhom: "Peaux atopiques, démangeaisons, cuir chevelu sensible en relais",
    precautions: "Sans parfum mais non stérile : sur une plaie ouverte, préférer un soin assainissant.",
    trust: 1,
  },
  "Atoderm Intensive Baume": {
    desc: "Un baume anti-grattage qui associe des lipides et un actif apaisant, pour casser le cercle grattage-lésion-grattage. Appliqué quotidiennement, il espace les crises plutôt qu'il ne les masque.",
    inci: "Aqua, Glycerin, Paraffinum Liquidum, Cetearyl Alcohol, Niacinamide, Butyrospermum Parkii Butter, Sucrose Stearate, Tocopherol, Xanthan Gum, Phenoxyethanol",
    use: "Appliquer deux fois par jour sur l'ensemble du corps, en insistant sur les zones qui se grattent.",
    when: "Matin et soir",
    amt: "Une noix par zone",
    order: "Après la toilette, sans rincer",
    texture: "Baume riche non collant",
    forWhom: "Peaux atopiques, poussées sèches, adultes et enfants",
    precautions: "Les corticoïdes prescrits ne se remplacent pas par ce baume : il accompagne le traitement, il ne le remplace pas.",
    trust: 1,
  },
  "Huile Prodigieuse": {
    desc: "Sept huiles végétales et de la vitamine E pour le visage, le corps et les cheveux, dans un flacon qu'on emporte. Le parfum est la signature du produit : si on ne l'aime pas, il n'y a pas de seconde raison de l'acheter.",
    inci: "Vitis Vinifera Seed Oil, Prunus Amygdalus Dulcis Oil, Corylus Avellana Seed Oil, Butyrospermum Parkii Butter, Camellia Oleifera Seed Oil, Macadamia Ternifolia Seed Oil, Borago Officinalis Seed Oil, Tocopherol, Parfum, Linalool, Limonene, Citral, Geraniol, Coumarin",
    use: "Vaporiser en un nuage sur le corps ou les cheveux, ou réchauffer quelques gouttes entre les paumes pour le visage, l'hiver.",
    when: "Matin ou soir, selon l'usage",
    amt: "Quelques gouttes — un nuage suffit sur les cheveux",
    order: "Après la crème sur le corps, avant le séchage sur les cheveux",
    texture: "Huile sèche multi-usages",
    forWhom: "Peaux normales à sèches, cheveux secs, usage estival",
    precautions: "Parfum riche : à éviter sur une peau réactive ou sur un cuir chevelu sensible. Non comédogène ne veut pas dire anodin sur une peau acnéique.",
  },
  "Lotion Hydratante Corps": {
    desc: "Une lotion fluide aux céramides et à l'acide hyaluronique, faite pour être appliquée en deux minutes après la douche sans attendre qu'elle pénètre. C'est la contenance familiale des peaux normales.",
    inci: "Aqua, Glycerin, Cetearyl Alcohol, Caprylic/Capric Triglyceride, Ceramide NP, Sodium Hyaluronate, Dimethicone, Cholesterol, Xanthan Gum, Phenoxyethanol",
    use: "Appliquer sur le corps entier après la douche, en massant rapidement.",
    when: "Une fois par jour",
    amt: "Deux à trois pressions par zone",
    order: "Juste après la douche",
    texture: "Lotion fluide à absorption rapide",
    forWhom: "Peaux normales à sèches, usage familial quotidien",
    precautions: "Insuffisante en hiver sur une peau très sèche : monter alors sur un baume relipidant.",
    trust: 1,
  },
  "Bariéderm Cica-Crème": {
    desc: "Une crème réparatrice qui assainit et protège les zones abîmées — pliures, gerçures, suites de soins — grâce au cuivre-zinc et à la glycérine. Elle isole la peau du frottement le temps qu'elle se refasse.",
    inci: "Aqua, Glycerin, Dimethicone, Copper Sulfate, Zinc Sulfate, Sodium Hyaluronate, Cetearyl Alcohol, Xanthan Gum, Phenoxyethanol",
    use: "Appliquer en couche fine sur la zone abîmée, une à deux fois par jour, en débordant largement.",
    when: "Matin et soir",
    amt: "Une noisette selon la zone",
    order: "Après la toilette, en dernier geste",
    texture: "Crème barrière assainissante",
    forWhom: "Zones irritées, pliures, suites de gestes techniques, tout âge",
    precautions: "Sur une plaie qui ne cicatrise pas en dix jours, ou qui chauffe, consultez : une crème ne traite pas une infection.",
  },
  "Lipikar Syndet AP+": {
    desc: "Un syndet sans savon qui lave les peaux atopiques sans les décaper, avec un pH respectueux et une base lavante douce. Il ne mousse presque pas — c'est normal, et c'est voulu.",
    inci: "Aqua, Glycerin, Sodium Laureth Sulfate, Coco-Betaine, Niacinamide, Butyrospermum Parkii Butter, Citric Acid, Sodium Chloride, Phenoxyethanol",
    use: "Faire mousser dans les mains mouillées, laver le corps, rincer à l'eau tiède.",
    when: "Une fois par jour, ou tous les deux jours",
    amt: "Une noisette par zone",
    order: "Premier geste de la douche, avant le baume",
    texture: "Crème lavante sans savon",
    forWhom: "Peaux atopiques, nourrissons, douches fréquentes",
    precautions: "L'eau trop chaude défait le travail de la crème lavante : tiède, jamais brûlante.",
    trust: 1,
  },
  "Atoderm Huile de Douche": {
    desc: "Une huile lavante qui se transforme en lait au contact de l'eau et relipide en même temps qu'elle lave. Pour les peaux très sèches, elle remplace le savon et raccourcit la routine.",
    inci: "Aqua, Glycerin, Peg-60 Glyceryl Cocoate, Coco-Betaine, Paraffinum Liquidum, Butyrospermum Parkii Butter, Sigesbeckia Orientalis Extract, Citric Acid, Phenoxyethanol",
    use: "Appliquer sur peau mouillée, masser, rincer — sans frotter avec un gant.",
    when: "À chaque douche",
    amt: "Deux pressions",
    order: "Après le shampooing, pour finir la douche",
    texture: "Huile lavante relipidante",
    forWhom: "Peaux très sèches, atopiques, sous la douche l'hiver",
    precautions: "Le sol de la douche devient glissant : à rincer soigneusement.",
  },
  "Rêve de Miel Gel Douche Ultra-Riche": {
    desc: "Un gel douche sans savon au miel et à l'huile d'olive, pensé pour les peaux qui tirent dès qu'elles sortent de l'eau. Il nettoie en laissant un film nourrissant.",
    inci: "Aqua, Glycerin, Sodium Cocoamphoacetate, Mel, Olea Europaea Fruit Oil, Coco-Glucoside, Citric Acid, Sodium Chloride, Sodium Benzoate, Parfum, Linalool, Limonene",
    use: "Faire mousser sur peau mouillée, rincer à l'eau tiède.",
    when: "À chaque douche",
    amt: "Une noisette",
    order: "Premier geste",
    texture: "Gel douche mielleux",
    forWhom: "Peaux sèches et sensibles, plaisir d'usage",
    precautions: "Contient du miel : à éviter chez un enfant de moins d'un an en cas d'ingestion, et dans les plis sur une peau réactive.",
    ageMin: 36,
  },
  "Crème Mains Cicaplast": {
    desc: "Une crème mains qui répare les gerçures et les doigts fendus sans laisser de film gras, pour ceux qui se lavent les mains vingt fois par jour. La zinc et le panthénol referment la peau.",
    inci: "Aqua, Glycerin, Dimethicone, Panthenol, Zinc Gluconate, Sodium Hyaluronate, Butyrospermum Parkii Butter, Cetearyl Alcohol, Phenoxyethanol",
    use: "Masser une noisette sur le dos des mains et entre les doigts après chaque lavage ou au besoin.",
    when: "Après chaque lavage, et le soir en couche épaisse",
    amt: "Une noisette",
    order: "Dernier geste avant de sortir ou de dormir",
    texture: "Crème mains réparatrice",
    forWhom: "Mains abîmées, métiers avec lavage fréquent, hiver",
    precautions: "Sur des mains qui saignent, une crème ne suffit pas : il faut une protection occlusive la nuit.",
  },
  "Crème Mains Rêve de Miel": {
    desc: "Une crème mains riche au miel et aux huiles, qui met du temps à pénétrer et c'est justement son intérêt : elle tient toute la nuit. La journée, préférez-la en petite quantité.",
    inci: "Aqua, Butyrospermum Parkii Butter, Mel, Glycerin, Prunus Amygdalus Dulcis Oil, Cera Alba, Tocopherol, Parfum, Linalool, Limonene, Citronellol, Geraniol",
    use: "Masser sur les mains, en insistant sur les cuticules et le bout des doigts.",
    when: "Le soir et en hiver",
    amt: "Une noisette",
    order: "Après la crème du jour, en couche plus épaisse la nuit",
    texture: "Crème mains riche",
    forWhom: "Mains très sèches, travail dehors, nuit",
    precautions: "Texture épaisse : à éviter juste avant de conduire ou de manipuler du papier.",
  },
  "Crème Pieds Réparatrice Urea 10%": {
    desc: "10 % d'urée pour ramollir les callosités et l'urée en plus forte dose pour les talons fendus : une crème qui fait un travail de ponçage chimique, sans douleur. Résultat visible en dix jours.",
    inci: "Aqua, Urea, Glycerin, Cetearyl Alcohol, Paraffinum Liquidum, Lactic Acid, Panthenol, Tocopherol, Xanthan Gum, Phenoxyethanol",
    use: "Appliquer le soir sur pieds propres et secs, en insistant sur les talons, puis chaussette en coton.",
    when: "Soir",
    amt: "Une noix par pied",
    order: "Après un bain tiède, dernier geste de la journée",
    texture: "Crème kératolytique épaisse",
    forWhom: "Talons fendus, callosités, pieds secs de l'été",
    precautions: "Contient de l'urée et de l'acide lactique : ne pas appliquer sur une plaie ouverte, ni sur un pied diabétique sans avis médical.",
  },
  "Huile Vergetures Bio": {
    desc: "Une huile de massage à la rose musquée et à l'argan, à masser chaque jour sur les zones qui s'étirent. Son efficacité tient surtout au geste quotidien, deux minutes, jamais au miracle.",
    inci: "Prunus Amygdalus Dulcis Oil, Rosa Canina Fruit Oil, Argania Spinosa Kernel Oil, Helianthus Annuus Seed Oil, Tocopherol",
    use: "Masser en mouvements circulaires sur le ventre, les hanches et les cuisses, matin et soir, pendant toute la grossesse et après.",
    when: "Matin et soir",
    amt: "Trois à quatre gouttes par zone",
    order: "Après la douche, sur peau humide",
    texture: "Huile de massage",
    forWhom: "Femmes enceintes, suites de prise de poids, vergetures récentes",
    precautions: "Aucune huile n'efface une vergeture installée : elle accompagne l'élasticité de la peau, elle ne répare pas une lésion faite.",
  },
  "Shampooing à l'Avoine": {
    desc: "Un shampooing surgras à l'avoine qui lave un cuir chevelu réactif sans le dégraisser, utilisable aussi souvent qu'on le souhaite. Il ne mousse pas beaucoup et c'est le prix de sa douceur.",
    inci: "Aqua, Sodium Laureth Sulfate, Coco-Glucoside, Avena Sativa Kernel Extract, Glycerin, Sodium Chloride, Citric Acid, Sodium Benzoate, Parfum",
    use: "Appliquer sur cheveux mouillés, masser le cuir chevelu, rincer. Une seule application suffit.",
    when: "À chaque lavage, aussi souvent que nécessaire",
    amt: "Une noisette",
    order: "Avant le baume",
    texture: "Shampooing surgras doux",
    forWhom: "Cuirs chevelus sensibles, usage fréquent, enfants",
    precautions: "Sur un cuir chevelu qui gratte avec des plaques, faites vérifier au comptoir : ce n'est pas toujours une sécheresse.",
  },
  "Anaphase+ Shampooing": {
    desc: "Un shampooing de cure qui accompagne la chute saisonnière avec de la vitamine B et des actifs stimulants, appliqué en massant. Il complète le traitement de fond, il ne le remplace pas.",
    inci: "Aqua, Sodium Laureth Sulfate, Coco-Betaine, Glycerin, Panthenol, Pyridoxine HCl, Biotin, Hydrolyzed Wheat Protein, Sodium Chloride, Citric Acid, Phenoxyethanol, Parfum, Linalool, Limonene",
    use: "Appliquer, masser le cuir chevelu une minute, laisser agir deux minutes, rincer.",
    when: "Trois à quatre lavages par semaine, en cure de trois mois",
    amt: "Deux noisettes",
    order: "Avant le soin anti-chute sans rinçage",
    texture: "Shampooing de cure",
    forWhom: "Chute saisonnière, cheveux fatigués, post-partum",
    precautions: "Une chute qui dure plus de trois mois ou laisse des zones dégarnies demande un avis médical, pas une cure.",
  },
  "Dercos Anti-Pelliculaire DS": {
    desc: "Un shampooing traitant qui élimine la levure responsable des pellicules et calme les démangeaisons dès les premiers lavages. On l'utilise en traitement, puis en entretien espacé.",
    inci: "Aqua, Sodium Laureth Sulfate, Coco-Betaine, Selenium Sulfide, Salicylic Acid, Glycerin, Sodium Chloride, Citric Acid, Phenoxyethanol, Parfum",
    use: "Appliquer sur cuir chevelu mouillé, masser, laisser agir trois minutes, rincer abondamment.",
    when: "Deux fois par semaine trois semaines, puis une fois par semaine",
    amt: "Une noisette par application",
    order: "En premier lavage, puis laisser agir pendant la douche",
    texture: "Shampooing traitant",
    forWhom: "Pellicules grasses, démangeaisons du cuir chevelu",
    precautions: "Contient du sulfure de sélénium : éviter le contact avec les yeux et les bijoux, et ne pas dépasser la fréquence indiquée.",
  },
  "Kelual DS Shampooing": {
    desc: "Un shampooing qui traite à la fois les pellicules et la rougeur du cuir chevelu, avec un actif antibactérien en plus de l'anti-levure. Il s'utilise peu mais franchement.",
    inci: "Aqua, Sodium Laureth Sulfate, Coco-Betaine, Piroctone Olamine, Zinc Pyrithione, Glycerin, Salicylic Acid, Sodium Chloride, Phenoxyethanol, Parfum",
    use: "Appliquer, masser, laisser agir trois minutes, rincer. Espacer dès que les symptômes s'apaisent.",
    when: "Deux fois par semaine, puis en entretien",
    amt: "Une noisette",
    order: "En premier lavage",
    texture: "Shampooing traitant fluide",
    forWhom: "Pellicules avec rougeurs, dermite du cuir chevelu",
    precautions: "Si la rougeur s'étend au-delà du cuir chevelu ou touche les sourcils, il s'agit d'autre chose : consultez.",
  },
  "Shampooing au Lait de Papyrus": {
    desc: "Un shampooing doux à base de lait de papyrus, pour espacer les lavages sur des cheveux qui regraissent vite. Il nettoie moins fort que les shampooings dégraissants et tient plus longtemps.",
    inci: "Aqua, Sodium Laureth Sulfate, Coco-Glucoside, Cyperus Esculentus Root Extract, Glycerin, Sodium Chloride, Citric Acid, Phenoxyethanol, Parfum",
    use: "Appliquer sur cheveux mouillés, masser, rincer ; renouveler si les cheveux sont très gras.",
    when: "Deux à trois fois par semaine",
    amt: "Une noisette",
    order: "Avant l'après-shampooing",
    texture: "Shampooing doux lacté",
    forWhom: "Cheveux qui regraissent vite, usage familial",
    precautions: "Sur des cheveux colorés ou très secs, il peut paraître asséchant au bout de plusieurs semaines : alterner.",
  },
  "Baume Après-Shampooing à la Mangue": {
    desc: "Un baume au beurre de mangue qui démêle les cheveux secs et cassants sans les alourdir, pensé pour être laissé deux minutes sous la douche. L'odeur tient sur la journée.",
    inci: "Aqua, Cetearyl Alcohol, Behentrimonium Chloride, Mangifera Indica Seed Butter, Glycerin, Panthenol, Tocopherol, Citric Acid, Phenoxyethanol, Parfum, Linalool, Benzyl Salicylate",
    use: "Appliquer sur les longueurs essorées, laisser deux minutes, démêler aux doigts puis rincer.",
    when: "Après chaque shampooing",
    amt: "Une noix sur les longueurs",
    order: "Après le shampooing, avant le coiffage",
    texture: "Baume riche démêlant",
    forWhom: "Cheveux secs, bouclés, abîmés par le soleil",
    precautions: "À ne pas poser sur les racines : le cuir chevelu n'a pas besoin de beurre de mangue.",
  },
  "Masque Nutri-Réparateur": {
    desc: "Un masque de réparation intense à laisser dix minutes, pour les cheveux qui cassent et se cassent encore après la mer. Il se fait une fois par semaine, pas à chaque lavage.",
    inci: "Aqua, Cetearyl Alcohol, Behentrimonium Chloride, Argania Spinosa Kernel Oil, Hydrolyzed Keratin, Panthenol, Glycerin, Tocopherol, Phenoxyethanol, Parfum, Linalool",
    use: "Appliquer sur cheveux essorés, laisser dix minutes, démêler, rincer abondamment.",
    when: "Une fois par semaine",
    amt: "Deux noix sur les longueurs",
    order: "Après le shampooing, à la place de l'après-shampooing",
    texture: "Masque intense",
    forWhom: "Cheveux très abîmés, décolorés, exposés au soleil",
    precautions: "Contient des protéines hydrolysées : sur des cheveux traités au lissage brésilien, vérifier la compatibilité au comptoir.",
  },
  "Dercos Aminexil Clinical 5 Femme": {
    desc: "Un traitement local à l'aminexil en monodoses, à appliquer au compte-gouttes sur un cuir chevelu propre, six semaines avant de juger. Il freine la chute, il ne fait pas repousser ce qui est parti.",
    inci: "Aqua, Alcohol Denat., Diaminopyrimidine Oxide, Glycerin, Arginine, Panthenol, Menthol, Peg-40 Hydrogenated Castor Oil, Phenoxyethanol",
    use: "Une monodose par application, en raies régulières sur cuir chevelu sec ou essoré, puis masser du bout des doigts. Ne pas rincer.",
    when: "Une fois par jour, trois mois",
    amt: "Une monodose",
    order: "Le soir, sur cuir chevelu propre et sec",
    texture: "Solution en monodoses",
    forWhom: "Chute de cheveux diffuse de la femme, chute saisonnière longue",
    precautions: "Contient de l'alcool et du menthol : sensation de fraîcheur normale. Une chute en plaques ou avec des zones lisses demande un dermatologue.",
  },
  "Neoptide Expert Sérum": {
    desc: "Un sérum en deux flacons, un jour sur deux, pour les chutes diffuses et les longueurs qui ne repoussent plus. Il se pose sans rinçage et ne graisse pas, ce qui le rend compatible avec un coiffage quotidien.",
    inci: "Aqua, Alcohol Denat., Glycerin, Caffeine, Panthenol, Niacinamide, Peg-40 Hydrogenated Castor Oil, Phenoxyethanol, Parfum",
    use: "Appliquer sur cuir chevelu sec, mèche par mèche, puis masser. Ne pas rincer.",
    when: "Un jour sur deux, trois mois",
    amt: "Une dose par application",
    order: "Le soir ou le matin avant coiffage",
    texture: "Sérum léger sans rinçage",
    forWhom: "Chute diffuse, cheveux fins, post-partum, post-covid",
    precautions: "Le compte-gouttes ne sert à rien sur une chute installée depuis plus de deux ans : demandez un avis avant d'acheter trois flacons.",
  },
  "Forcapil Cheveux & Ongles": {
    desc: "Une cure de vitamines et d'oligo-éléments — biotine, zinc, vitamines B — pour les cheveux et les ongles qui poussent mal. Le bénéfice se voit au bout de deux mois, jamais en dix jours.",
    inci: "Vitamines B (B5, B6, B8 biotine, B9), Zinc, Cuivre, Acides aminés soufrés, Extrait de millet, Gélule végétale",
    use: "Une gélule le matin au petit-déjeuner et une le soir, avec un verre d'eau.",
    when: "Matin et soir, cure de trois mois",
    amt: "2 gélules par jour",
    order: "Au cours d'un repas",
    texture: "Gélules",
    forWhom: "Cheveux fragiles, ongles qui se dédoublent, carences alimentaires",
    precautions: "Contient du zinc et des vitamines : à ne pas associer à une autre supplémentation en zinc sans avis, et à signaler à votre médecin.",
    ageMin: 180,
  },
  "Sensinol Shampooing Physioprotecteur": {
    desc: "Un shampooing sans sulfates ni parfum pour les cuirs chevelus qui réagissent à tout, y compris aux shampooings doux. Sa formule courte en fait souvent le dernier recours avant l'avis dermatologique.",
    inci: "Aqua, Sodium Cocoyl Isethionate, Coco-Betaine, Glycerin, Panthenol, Sodium Chloride, Citric Acid, Sodium Benzoate",
    use: "Appliquer une noisette sur cheveux mouillés, masser doucement, rincer.",
    when: "À chaque lavage",
    amt: "Une noisette",
    order: "Seul, sans après-shampooing parfumé derrière",
    texture: "Shampooing sans sulfates",
    forWhom: "Cuirs chevelus réactifs, intolérances aux shampooings courants",
    precautions: "Mousse peu : cela ne veut pas dire qu'il lave mal. Si la gêne persiste, ce n'est pas le produit qu'il faut changer mais la question qu'on se pose.",
  },
};
