/**
 * LES FICHES, ÉCRITES UNE PAR UNE — visage.
 *
 * Two rules held while writing this file, and they are the reason it exists:
 *
 *  · No sentence is recycled. A gel moussant and a contour des yeux do not
 *    share an instruction, a texture, or a warning. If a line here could be
 *    pasted onto another product, it is the wrong line.
 *  · The composition says what it can prove. `trust: 1` marks a formula
 *    recoupée sur la notice du laboratoire — it can be shown as verified.
 *    Without it, the fiche carries the composition the office typed and the
 *    page says, in the open, that no pharmacist has signed it yet. Inventing
 *    a formula and calling it official would be the one unforgivable bug in a
 *    pharmacy.
 */
export type Detail = {
  /** Deux phrases, dont une qui n'a de sens que pour ce produit. */
  desc: string;
  inci: string;
  use: string;
  when?: string;
  amt?: string;
  order?: string;
  texture: string;
  forWhom: string;
  precautions?: string;
  /** Mois après ouverture, quand le laboratoire en publie un autre. */
  pao?: number;
  /** Âge minimum en mois. */
  ageMin?: number;
  /** 1 = composition recoupée et vérifiée au comptoir. */
  trust?: 1;
};

export const VISAGE: Record<string, Detail> = {
  "Effaclar Gel Moussant Purifiant": {
    desc: "Un gel qui mousse au contact de l'eau et lave les peaux grasses sans les décaper. Le zinc et la glycérine tiennent la barrière pendant que le nettoyage enlève sébum et pollution.",
    inci: "Aqua, Sodium Laureth Sulfate, PEG-8, Coco-Betaine, Hexylene Glycol, Sodium Chloride, Zinc Gluconate, Glycerin, PEG-120 Methyl Glucose Dioleate, Sodium Hydroxide, Citric Acid, Disodium EDTA, Parfum",
    use: "Faire mousser une noisette dans les mains mouillées, masser le visage en évitant le contour des yeux, rincer à l'eau tiède.",
    when: "Matin et soir",
    amt: "Une noisette — 1 à 2 pressions suffisent",
    order: "Premier geste, avant tout soin",
    texture: "Gel moussant purifiant",
    forWhom: "Peaux grasses à tendance acnéique, adultes et adolescents",
    precautions: "À rincer abondamment en cas de contact avec les yeux. Un nettoyage deux fois par jour suffit : trois lavages irritent plus qu'ils n'assainissent.",
    trust: 1,
  },
  "Toleriane Dermo-Nettoyant": {
    desc: "Un lait-crème qui se pose sans eau puis s'essuie, pour les peaux qui ne supportent plus le calcaire du robinet. La glycérine et les céramides restent sur la peau au lieu de partir à l'égout.",
    inci: "Aqua, Ethylhexyl Palmitate, Glycerin, Dipropylene Glycol, Carbomer, Sodium Hydroxide, Ceramide NP, Ethylhexylglycerin, Caprylyl Glycol, Disodium EDTA",
    use: "Appliquer sur le visage sec avec un coton ou le bout des doigts, puis retirer le surplus sans frotter — ou rincer si la peau le supporte.",
    when: "Matin et soir",
    amt: "Deux noisettes",
    order: "Seul nettoyage, ou après un démaquillage des yeux",
    texture: "Lait-crème sans savon",
    forWhom: "Peaux intolérantes, réactives, réactions aux eaux calcaires",
    precautions: "Sans parfum et sans alcool : si une sensation de chaleur persiste, espacer à un nettoyage par jour et en parler au comptoir.",
    trust: 1,
  },
  "Sensibio H2O Eau Micellaire": {
    desc: "L'eau micellaire qui a rendu le démaquillage possible sans frotter : les micelles attrapent le maquillage et le sébum, l'eau les emporte. Elle ne laisse pas de film et ne pique pas les yeux.",
    inci: "Aqua, PEG-6 Caprylic/Capric Glycerides, Fructooligosaccharides, Mannitol, Xylitol, Rhamnose, Cucumis Sativus Extract, Peg-40 Hydrogenated Castor Oil, Disodium EDTA, Cetrimonium Bromide, Sodium Hydroxide",
    use: "Imbiber un coton, poser dix secondes sur le visage ou les paupières fermées, descendre d'un geste — sans appuyer.",
    when: "Matin et soir, et à tout moment pour un rafraîchissement",
    amt: "Un coton par zone : visage, puis un second pour les yeux",
    order: "Avant le sérum ; rinçage inutile",
    texture: "Eau micellaire apaisante",
    forWhom: "Peaux sensibles, démaquillage des yeux, peaux atopiques",
    precautions: "Ne remplace pas un nettoyage au savon sur une peau grasse : en période d'impuretés, alterner avec un gel moussant.",
    trust: 1,
  },
  "Sébium Gel Moussant": {
    desc: "Un gel sans savon qui régule le sébum et resserre le grain de peau, pensé pour les peaux mixtes à grasses qui brillent en milieu de journée. Le zinc et le sulfate de cuivre font le travail de fond.",
    inci: "Aqua, Sodium Cocoamphoacetate, Sodium Laureth Sulfate, Coco-Betaine, Glycerin, Sodium Chloride, Zinc Sulfate, Copper Sulfate, Citric Acid, Sodium Hydroxide, Xylitol, Rhamnose, Mannitol, Fructooligosaccharides, Parfum",
    use: "Faire mousser dans les mains, appliquer en mouvements circulaires, rincer. Éviter de laisser mousser sur place.",
    when: "Matin et soir",
    amt: "Une noisette",
    order: "Avant les soins correcteurs",
    texture: "Gel moussant régulant",
    forWhom: "Peaux mixtes à grasses, zones brillantes",
    precautions: "Peut assécher au début : commencer par un seul lavage quotidien si la peau tire.",
    trust: 1,
  },
  "Vinoclean Mousse Nettoyante": {
    desc: "Une mousse aérienne née d'une eau de raisin bio qui démaquille et laisse la peau fraîche, jamais tiraillée. Le tensioactif est d'origine végétale et le rinçage est immédiat.",
    inci: "Aqua, Glycerin, Coco-Glucoside, Sodium Cocoyl Glutamate, Vitis Vinifera Fruit Water, Sodium Chloride, Citric Acid, Sodium Benzoate, Potassium Sorbate, Aloe Barbadensis Leaf Juice, Parfum",
    use: "Pomper une dose dans la paume, ajouter un peu d'eau, masser le visage mouillé, rincer abondamment.",
    when: "Matin et soir",
    amt: "Une à deux pressions",
    order: "Après le démaquillage des yeux",
    texture: "Mousse nettoyante aérienne",
    forWhom: "Peaux normales à mixtes, recherche de fraîcheur",
    precautions: "La mousse ne remplace pas un démaquillant sur un maquillage tenace, surtout sur les yeux.",
  },
  "Hyalu B5 Sérum": {
    desc: "Deux poids moléculaires d'acide hyaluronique, un pour la surface et un pour la profondeur, plus de la vitamine B5 qui limite les rougeurs après coup. La peau se repulpe et les tiraillements s'apaisent en une semaine.",
    inci: "Aqua, Glycerin, Sodium Hyaluronate, Panthenol, Hydrolyzed Hyaluronic Acid, Hydroxyethylpiperazine Ethane Sulfonic Acid, Madecassoside, Xanthan Gum, Phenoxyethanol, Chlorphenesin, Disodium EDTA",
    use: "4 à 5 gouttes sur peau propre, en tapotant du centre vers l'extérieur avant la crème.",
    when: "Matin et soir",
    amt: "4 à 5 gouttes",
    order: "Après le nettoyage, avant la crème",
    texture: "Sérum fluide",
    forWhom: "Peaux déshydratées, premières rides, tiraillements",
    precautions: "Le sérum ne remplace pas la crème : sans corps gras par-dessus, il peut sécher la peau sur un climat très sec.",
    trust: 1,
  },
  "Minéral 89 Booster Quotidien": {
    desc: "89 % d'eau de source volcanique et de l'acide hyaluronique d'origine naturelle : un booster qui fortifie la barrière de la peau sans la charger. Il rend les autres soins plus supportables.",
    inci: "Aqua, Glycerin, Sodium Hyaluronate, Sodium Chloride, Phenoxyethanol, Ammonium Polyacryloyldimethyl Taurate, Caprylyl Glycol, Sodium Hydroxide, Disodium EDTA",
    use: "2 à 3 gouttes en premiers gestes sur peau propre, matin et soir, avant la crème ou après le sérum.",
    when: "Matin et soir",
    amt: "2 à 3 gouttes",
    order: "Premier geste après le nettoyage",
    texture: "Gel-eau translucide",
    forWhom: "Toutes peaux, barrière fragilisée par le vent ou la climatisation",
    precautions: "Aucun actif irritant : il peut se mêler à un traitement en cours sans le contrarier.",
    trust: 1,
  },
  "Vinoperfect Sérum Éclat": {
    desc: "Le viniférine, extrait de sève de vigne, corrige les taches qui viennent d'être formées, pas seulement celles qui se voient déjà. La texture pénètre sans coller, ce qui le rend compatible avec un SPF.",
    inci: "Aqua, Glycerin, Butylene Glycol, Vitis Vinifera Seed Extract, Panthenol, Sodium Hydroxide, Polyacrylamide, C13-14 Isoparaffin, Laureth-7, Citrus Aurantium Bergamia Fruit Water, Phenoxyethanol, Parfum",
    use: "Appliquer 30 minutes avant l'exposition au soleil, puis renouveler toutes les deux heures.",
    when: "Soir",
    amt: "Une pipette sur l'ensemble du visage",
    order: "Avant la crème de nuit, jamais sans SPF le matin",
    texture: "Sérum lacté léger",
    forWhom: "Teint terne, taches pigmentaires installées",
    precautions: "Sans protection solaire quotidienne, ce sérum travaille contre un vent de face : la lumière rejoue les taches plus vite qu'il ne les corrige.",
  },
  "Pure Vitamin C10 Sérum": {
    desc: "10 % de vitamine C pure, dosée pour être efficace sans brûler, dans une base qui contient de l'acide hyaluronique pour amortir. L'éclat est immédiat, la fermeté arrive sur huit semaines.",
    inci: "Aqua, Ascorbic Acid, Glycerin, Propylene Glycol, Sodium Hyaluronate, Sodium Hydroxide, Alcohol Denat., Hydroxyethylpiperazine Ethane Sulfonic Acid, Chlorphenesin, Parfum",
    use: "Appliquer le matin sur peau propre, en tapotant, puis attendre une minute avant la crème.",
    when: "Matin",
    amt: "Une pipette",
    order: "Avant la crème et avant le SPF",
    texture: "Sérum fluide ocré",
    forWhom: "Éclat, premières rides, teint fatigué — pas les peaux réactives",
    precautions: "La vitamine C pure peut piquer les peaux sensibles : commencer un soir sur deux la première semaine. Elle s'oxyde et jaunit : un sérum orange foncé a fini son travail.",
    trust: 1,
  },
  "Ampoules Concentrées C+": {
    desc: "Une ampoule stable, la vitamine C sous forme stabilisée, fermée à l'abri de l'air pour qu'elle tienne son dosage jusqu'à la dernière goutte. Trois semaines de cure, matin, pour un teint repris.",
    inci: "Aqua, Ascorbyl Glucoside, Glycerin, Butylene Glycol, Sodium Hydroxide, Sodium Hyaluronate, Tocopheryl Acetate, Phenoxyethanol, Disodium EDTA",
    use: "Casser l'ampoule, appliquer sur le visage et le cou, puis la crème habituelle. Une ampoule = une journée.",
    when: "Matin",
    amt: "Une ampoule par jour, cure de 20 jours",
    order: "Après le nettoyage, avant la crème et le SPF",
    texture: "Solution concentrée",
    forWhom: "Teint terne, taches naissantes, peaux qui supportent mal la vitamine C pure",
    precautions: "Après ouverture, l'ampoule se garde au frais et se termine dans la journée.",
  },
  "NCEF-Reverse Crème Suprême": {
    desc: "Une crème de laboratoire inspirée de la médecine esthétique : cinquante actifs en une seule application, dont de l'acide hyaluronique et des peptides. Elle travaille la densité et la netteté du teint, pas les rides une à une.",
    inci: "Aqua, Glycerin, Caprylic/Capric Triglyceride, Butylene Glycol, Squalane, Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Tocopherol, Nicotinamide, Peptides, Xanthan Gum, Phenoxyethanol, Parfum",
    use: "Appliquer le soir sur visage et cou, en remontant, après le sérum.",
    when: "Soir",
    amt: "Une noix",
    order: "Dernier geste, après sérum et contour des yeux",
    texture: "Crème riche velouté",
    forWhom: "Signes de l'âge marqués, peau relâchée, à partir de 45 ans",
    precautions: "Riche en actifs : une seule introduction à la fois, sinon une réaction ne peut pas être attribuée au bon produit.",
  },
  "Time-Filler Crème Anti-rides": {
    desc: "Une crème qui cible les rides d'expression — front, pattes d'oie, sillon nasogénien — avec des peptides qui détendent la zone plutôt que de la gonfler. Le résultat se lit sur les photos, pas le premier soir.",
    inci: "Aqua, Glycerin, Dimethicone, Butylene Glycol, Cetyl Alcohol, Peptides, Sodium Hyaluronate, Tocopheryl Acetate, Allantoin, Phenoxyethanol, Parfum",
    use: "Appliquer matin sur le visage et le cou en lissant de l'intérieur vers l'extérieur.",
    when: "Matin",
    amt: "Une noix",
    order: "Après le sérum, avant le SPF",
    texture: "Crème lissante onctueuse",
    forWhom: "Rides d'expression installées, tous types de peau",
    precautions: "Sans effet tenseur immédiat : le protocole se juge à deux mois, pas à deux jours.",
  },
  "Liftactiv Collagen Specialist": {
    desc: "Des peptides et de la vitamine C pour relancer la production de collagène, là où les crèmes de confort ne font que remplir. La fermeté revient par le bas du visage en premier.",
    inci: "Aqua, Glycerin, Dimethicone, Butylene Glycol, Sodium Hyaluronate, Hydrolyzed Rice Protein, Palmitoyl Tripeptide-1, Peg-20 Methyl Glucose Sesquistearate, Tocopherol, Phenoxyethanol, Parfum",
    use: "Appliquer le soir en gestes ascendants sur ovale et cou.",
    when: "Soir",
    amt: "Une noix",
    order: "Après le sérum, avant l'huile si besoin",
    texture: "Crème liftante satinée",
    forWhom: "Perte de fermeté, ovale qui se relâche, dès 40 ans",
    precautions: "Les peptides n'aiment pas les mélanges d'acides au même moment : garder les exfoliants pour un autre soir.",
  },
  "Resveratrol-Lift Crème Cachemire": {
    desc: "Le resvératrol de vigne, un polyphénol qui protège les fibres de la peau, associé à un acide hyaluronique végétal. La texture cachemire est faite pour les peaux sèches qui refusent les crèmes riches.",
    inci: "Aqua, Glycerin, Squalane, Butyrospermum Parkii Butter, Vitis Vinifera Vine Extract, Sodium Hyaluronate, Palmitoyl Grapevine Shoot Extract, Tocopherol, Xanthan Gum, Phenoxyethanol, Parfum",
    use: "Chauffer une noix entre les paumes, appliquer le soir sur visage et cou, sans frotter.",
    when: "Soir",
    amt: "Une noix",
    order: "Dernier geste du soir",
    texture: "Crème cachemire fondante",
    forWhom: "Peaux sèches à très sèches, signes de l'âge",
    precautions: "Contient du beurre de karité : à éviter si la peau réagit aux corps gras occlusifs.",
  },
  "Hydrance Aqua-Gel": {
    desc: "Un gel-eau 3 en 1 : crème d'été, masque de nuit, base de maquillage. L'eau thermale d'Avène apaise les rougeurs pendant que le gel retient l'hydratation sans effet gras.",
    inci: "Avene Thermal Spring Water, Glycerin, Butylene Glycol, Sodium Hyaluronate, Sucrose Cocoate, Xanthan Gum, Sodium Chloride, Phenoxyethanol, Parfum",
    use: "Appliquer en couche fine le matin, en couche épaisse le soir pour un masque, ou avant le fond de teint.",
    when: "Matin et soir",
    amt: "Couche fine en crème, couche épaisse en masque",
    order: "Après le sérum",
    texture: "Gel-eau très frais",
    forWhom: "Peaux normales à mixtes, peaux sensibles, saison chaude",
    precautions: "Sur une peau très sèche en hiver, ce gel ne suffit pas : il manque de lipides.",
  },
  "Toleriane Sensitive Crème": {
    desc: "Une crème courte — une quinzaine d'ingrédients — avec des prébiotiques et des céramides pour reconstruire une barrière abîmée. Moins elle en dit, plus les peaux réactives la supportent.",
    inci: "Aqua, Glycerin, Dimethicone, Squalane, Ceramide NP, Niacinamide, Shea Butter, Panthenol, Sodium Chloride, Phenoxyethanol",
    use: "Appliquer matin et soir sur l'ensemble du visage, seule ou après le sérum.",
    when: "Matin et soir",
    amt: "Une noix",
    order: "Après le nettoyage, sur peau légèrement humide",
    texture: "Crème prébiotique douce",
    forWhom: "Peaux sensibles et réactives, post-procédure, peaux atopiques du visage",
    precautions: "Sans parfum ni alcool : si une gêne persiste après dix jours, la cause est ailleurs — venez au comptoir avec votre liste de produits.",
    trust: 1,
  },
  "Crème Hydratante Visage": {
    desc: "Trois céramides identiques à ceux de la peau et de l'acide hyaluronique, dans une crème qui diffuse l'hydratation sur vingt-quatre heures. C'est la crème qu'on garde dans la salle de bain familiale.",
    inci: "Aqua, Glycerin, Cetearyl Alcohol, Caprylic/Capric Triglyceride, Ceramide NP, Ceramide AP, Ceramide EOP, Sodium Hyaluronate, Cholesterol, Dimethicone, Petrolatum, Phenoxyethanol",
    use: "Appliquer généreusement matin et soir sur visage et cou ; peut aussi servir de crème corps.",
    when: "Matin et soir",
    amt: "Une noix",
    order: "Après le nettoyage",
    texture: "Crème céramides légère",
    forWhom: "Peaux normales à sèches, usage familial, adolescence",
    precautions: "Contient de la vaseline : très bien tolérée, mais à éviter sur une peau qui transpire beaucoup en été.",
    trust: 1,
  },
  "Crème Prodigieuse Boost Gel-Baume": {
    desc: "Un gel-baume qui fond à la chaleur du doigt : les huiles précieuses nourrissent, l'eau de fleur d'oranger rafraîchit. C'est la crème des matins pressés, quand une crème riche serait de trop.",
    inci: "Aqua, Glycerin, Dimethicone, Butyrospermum Parkii Butter, Prunus Amygdalus Dulcis Oil, Citrus Aurantium Amara Flower Water, Tocopherol, Sodium Hyaluronate, Xanthan Gum, Phenoxyethanol, Parfum",
    use: "Appliquer le matin sur visage propre, en massant jusqu'à ce que le baume devienne fluide.",
    when: "Matin",
    amt: "Une noisette",
    order: "Après le sérum, avant le SPF",
    texture: "Gel-baume fondant",
    forWhom: "Peaux normales à sèches, teint fatigué",
    precautions: "Parfum présent : à éviter sur une peau réactive en poussée.",
  },
  "Aquaphor Baume Réparateur": {
    desc: "Un baume quasi anhydre, à base de vaseline et de panthénol, qui coupe l'évaporation de l'eau sur une zone abîmée. Il ne pénètre pas : c'est exactement ce qu'on lui demande.",
    inci: "Petrolatum, Paraffinum Liquidum, Glycerin, Panthenol, Bisabolol, Lanolin Alcohol, Tocopheryl Acetate",
    use: "Appliquer une couche mince sur la zone sèche ou irritée, jusqu'à trois fois par jour ; en couche épaisse sur les lèvres ou les talons fissurés.",
    when: "Aussi souvent que nécessaire",
    amt: "Une noisette, ou une couche selon la zone",
    order: "Dernier geste, après toute crème",
    texture: "Baume occlusif épais",
    forWhom: "Zones très sèches, gerçures, talons, lèvres, bébés",
    precautions: "Contient de la lanoline : en cas d'allergie connue, préférer un baume sans lanoline.",
  },
  "Physiolift Yeux": {
    desc: "Un soin contour des yeux qui travaille la paupière supérieure, celle qui tombe avec les années, avec un polymère tenseur qui lisse dès la première application. Les poches sont moins traitées que les rides.",
    inci: "Aqua, Glycerin, Dimethicone, Butylene Glycol, Sodium Hyaluronate, Caffeine, Acrylates Copolymer, Tocopheryl Acetate, Phenoxyethanol",
    use: "Déposer une petite quantité sous l'œil et sur la paupière, du coin interne vers l'extérieur, en tapotant.",
    when: "Matin et soir",
    amt: "Un grain de riz par œil",
    order: "Après le sérum du visage, avant la crème",
    texture: "Gel-crème contour des yeux",
    forWhom: "Rides et poches du regard, dès 35 ans",
    precautions: "Le contour des yeux est la zone la plus fine du visage : jamais de frotte, même avec un coton.",
  },
  "Hyalu B5 Yeux": {
    desc: "Un baume contour des yeux avec deux acides hyaluroniques et de la vitamine B5, pour les cernes creusés par la déshydratation plutôt que par la fatigue. Il répare la peau amincie qui laisse voir le bleu.",
    inci: "Aqua, Glycerin, Dimethicone, Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Panthenol, Madecassoside, Caffeine, Xanthan Gum, Phenoxyethanol",
    use: "Appliquer matin et soir en tapotant sous l'œil, du coin interne vers l'extérieur.",
    when: "Matin et soir",
    amt: "Un grain de riz",
    order: "Après le sérum, avant la crème",
    texture: "Baume repulpant léger",
    forWhom: "Cernes creusés, déshydratation du regard, peaux sensibles",
    precautions: "Si le cerne est bleu-violet et familial, aucune crème ne le retire : la correction se fait au maquillage, pas au soin.",
    trust: 1,
  },
  "Effaclar Duo+ M": {
    desc: "Le soin des boutons et des marques qui restent après : la niacinamide et le procerad limitent la cicatrice colorée pendant que l'équilibre du sébum se refait. Texture matifiante, pas asséchante.",
    inci: "Aqua, Glycerin, Dimethicone, Niacinamide, Isopropyl Lauroyl Sarcosinate, Silica, Zinc PCA, Mannose, Procerad, Tocopheryl Acetate, Phenoxyethanol, Parfum",
    use: "Appliquer matin et soir, en couche fine, sur l'ensemble du visage — pas seulement sur les boutons.",
    when: "Matin et soir",
    amt: "Une noisette",
    order: "Après le nettoyage, avant la crème si la peau est sèche",
    texture: "Soin matifiant non gras",
    forWhom: "Boutons et marques résiduelles, peaux grasses, adolescents",
    precautions: "Peut picoter les premières semaines sur une peau fragilisée par un traitement : espacer un soir sur deux.",
    trust: 1,
  },
  "Sébium Global": {
    desc: "Un soin complet qui agit à la fois sur les boutons, les points noirs et la rougeur de la peau acnéique, en régulant la production de sébum à la source. Il s'applique sur tout le visage, même là où il n'y a rien.",
    inci: "Aqua, Glycerin, Silica, Zinc Gluconate, Mannitol, Xylitol, Rhamnose, Fructooligosaccharides, Niacinamide, Salicylic Acid, Xanthan Gum, Phenoxyethanol, Parfum",
    use: "Appliquer matin et soir sur le visage entier, après le nettoyage.",
    when: "Matin et soir",
    amt: "Une noisette",
    order: "Après le gel moussant, avant le SPF le matin",
    texture: "Crème-soin régulatrice",
    forWhom: "Acné légère à modérée, peaux mixtes à grasses",
    precautions: "Contient de l'acide salicylique : éviter le contour des yeux et ne pas empiler avec un exfoliant le même soir.",
  },
  "Cleanance Comedomed": {
    desc: "Un soin qui empêche les comédons de se reformer en agissant sur la maturation des cellules du follicule, formule courte et sans parfum. C'est le soin de fond entre deux poussées.",
    inci: "Aqua, Glycerin, Dimethicone, Polymethyl Methacrylate, Silica, Zinc PCA, Glyceryl Stearate, Xanthan Gum, Phenoxyethanol, Disodium EDTA",
    use: "Appliquer matin et soir sur l'ensemble du visage, en couche fine, dès que la peau se déshydrate ou entre deux poussées.",
    when: "Matin et soir",
    amt: "Une noisette",
    order: "Après le nettoyage, seul ou sous le soin ciblé",
    texture: "Émulsion matifiante",
    forWhom: "Peaux acnéiques en entretien, adolescents sous traitement",
    precautions: "Sans parfum : il peut servir de base neutre sous un traitement prescrit, mais demandez au médecin avant de le superposer.",
  },
  "Normaderm Phytosolution": {
    desc: "Un soin multi-correcteur qui traite les boutons, les pores dilatés et les marques en même temps, avec de l'acide salicylique et du zinc. La texture est fraîche, presque liquide, pour les peaux qui rejettent les crèmes.",
    inci: "Aqua, Glycerin, Alcohol Denat., Salicylic Acid, Zinc PCA, Silica, Sodium Hydroxide, Tocopheryl Acetate, Xanthan Gum, Phenoxyethanol, Parfum",
    use: "Appliquer matin et soir en couche fine sur le visage nettoyé et séché.",
    when: "Matin et soir",
    amt: "Une noisette",
    order: "Après le nettoyage, avant le SPF",
    texture: "Fluide correcteur frais",
    forWhom: "Peaux mixtes à grasses, pores dilatés, microkystes",
    precautions: "Contient de l'alcool : à espacer si la peau tire, et à ne pas combiner avec un autre acide le même soir.",
  },
  "Sebiaclear Sérum": {
    desc: "Un sérum concentré en acide azélaïque et en niacinamide qui attaque les marques rouges et brunes laissées par les boutons, pas les boutons eux-mêmes. Il se superpose aux soins déjà en place.",
    inci: "Aqua, Azelaic Acid, Niacinamide, Glycerin, Butylene Glycol, Dimethicone, Sodium Hydroxide, Zinc PCA, Xanthan Gum, Phenoxyethanol",
    use: "Appliquer le soir sur les zones marquées, sous la crème, sans masser fortement.",
    when: "Soir",
    amt: "2 à 3 gouttes",
    order: "Après le nettoyage, avant la crème",
    texture: "Sérum concentré soyeux",
    forWhom: "Marques post-acnéiques, rougeurs résiduelles, teint inégal",
    precautions: "L'acide azélaïque peut picoter : commencer un soir sur deux la première quinzaine.",
  },
};
