#!/usr/bin/env node
/**
 * Cléopâtre — isolated development PostgreSQL.
 *
 * The project must run from a clean checkout with a single command, without
 * touching a PostgreSQL instance the developer already uses for something else.
 *
 * Resolution order:
 *   1. If DATABASE_URL points at a *reachable* server and the local cluster is
 *      not requested, keep it untouched and exit 0. (Never modify, stop or drop
 *      a server we did not start.)
 *   2. Otherwise boot a *project-local* cluster under `.devdb/` using the
 *      `embedded-postgres` binaries that ship with the dependency.
 *
 * Lifecycle note — why this script calls `pg_ctl` instead of `pg.start()`:
 * `embedded-postgres` registers a process-exit hook that shuts down every
 * cluster it started, so a server started through its API dies the moment the
 * setup script finishes. `persistent: true` keeps the *data* but not the
 * *server*. `pg_ctl start` daemonises the postmaster instead, which is what a
 * development session needs. The library is still used for `initdb`, where its
 * platform handling is useful.
 *
 * Usage:
 *   node scripts/dev-db.mjs start     # boot and prepare (idempotent)
 *   node scripts/dev-db.mjs stop      # stop the project-local cluster
 *   node scripts/dev-db.mjs status    # print connection info
 *   node scripts/dev-db.mjs reset     # wipe + recreate the local cluster
 *   node scripts/dev-db.mjs url       # print the DATABASE_URL to export
 */
import { randomBytes } from "node:crypto";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { createConnection } from "node:net";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DEVDB = join(ROOT, ".devdb");
const DATA_DIR = join(DEVDB, "data");
const LOG_DIR = join(DEVDB, "logs");
const LOG_FILE = join(LOG_DIR, "postgres.log");
const STATE_FILE = join(DEVDB, "state.json");

const DEFAULT_PORT = Number(process.env.DEV_DB_PORT ?? 5433);
const USER = "cleopatre";
const PASSWORD = "cleopatre";
const DATABASE = process.env.DEV_DB_NAME ?? "cleopatre_dev";

const localUrl = (port = DEFAULT_PORT) =>
  `postgresql://${USER}:${PASSWORD}@127.0.0.1:${port}/${DATABASE}`;

function log(message) {
  process.stdout.write(`\u001b[36m[dev-db]\u001b[0m ${message}\n`);
}
function warn(message) {
  process.stdout.write(`\u001b[33m[dev-db]\u001b[0m ${message}\n`);
}

// ─────────────────────────────────────────────────────────────── environment

function readEnvFile() {
  const file = join(ROOT, ".env");
  if (!existsSync(file)) return {};
  const out = {};
  for (const line of readFileSync(file, "utf8").split(/\r?\n/)) {
    const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/.exec(line);
    if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
  return out;
}

function databaseUrlFromEnv() {
  if (process.env.DATABASE_URL) return process.env.DATABASE_URL;
  return readEnvFile().DATABASE_URL ?? null;
}

/**
 * Point `.env` at the cluster this script owns.
 *
 * Without this, a developer who copies `.env.example` (which points at an empty
 * placeholder on port 5432) and then starts the local cluster would have
 * `db:push` and the app connect to the *old* address — a failure that looks
 * like a database outage but is only a stale variable. Only the DATABASE_URL
 * line is rewritten, and only for a cluster this project started.
 */
function writeEnvDatabaseUrl(url) {
  const file = join(ROOT, ".env");
  if (!existsSync(file)) {
    // A complete development environment, not half of one: the application
    // refuses to run in production without a real SESSION_SECRET, and a bare
    // DATABASE_URL would leave the recipient with a server that 500s.
    const secret = randomBytes(32).toString("hex");
    const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
    writeFileSync(
      file,
      [
        "# Generated by scripts/dev-db.mjs for local development.",
        "# Replace every value below before deploying.",
        `DATABASE_URL=${url}`,
        `SESSION_SECRET=${secret}`,
        `NEXT_PUBLIC_SITE_URL=${siteUrl}`,
        "",
      ].join("\n"),
    );
    log("created .env (DATABASE_URL, random SESSION_SECRET, NEXT_PUBLIC_SITE_URL)");
    return;
  }
  const lines = readFileSync(file, "utf8").split(/\r?\n/);
  const at = lines.findIndex((line) => /^\s*DATABASE_URL\s*=/.test(line));
  if (at >= 0) {
    if (lines[at].trim() === `DATABASE_URL=${url}`) return;
    lines[at] = `DATABASE_URL=${url}`;
  } else {
    if (lines.length && lines[lines.length - 1].trim() !== "") lines.push("");
    lines.push(`DATABASE_URL=${url}`);
  }
  writeFileSync(file, lines.join("\n"));
  log("updated DATABASE_URL in .env");
}

function parseUrl(url) {
  try {
    const u = new URL(url);
    return { host: u.hostname, port: Number(u.port || 5432) };
  } catch {
    return null;
  }
}

/** TCP reachability of a Postgres port — no credentials, no side effects. */
function isPortOpen(host, port, timeout = 900) {
  return new Promise((done) => {
    const socket = createConnection({ host, port });
    const finish = (ok) => {
      socket.removeAllListeners();
      socket.destroy();
      done(ok);
    };
    socket.setTimeout(timeout);
    socket.once("connect", () => finish(true));
    socket.once("timeout", () => finish(false));
    socket.once("error", () => finish(false));
  });
}

function readState() {
  try {
    return JSON.parse(readFileSync(STATE_FILE, "utf8"));
  } catch {
    return null;
  }
}

function writeState(value) {
  mkdirSync(dirname(STATE_FILE), { recursive: true });
  writeFileSync(STATE_FILE, `${JSON.stringify(value, null, 2)}\n`);
}
function clearState() {
  try {
    rmSync(STATE_FILE, { force: true });
  } catch {}
}

// ───────────────────────────────────────────────────────────────── binaries

/**
 * Locate the PostgreSQL binaries shipped with `embedded-postgres`. npm installs
 * exactly one `@embedded-postgres/<platform>` package (the others are skipped by
 * os/cpu fields), so scanning is both safe and portable.
 */
function binDir() {
  const packages = join(ROOT, "node_modules", "@embedded-postgres");
  if (!existsSync(packages)) return null;
  for (const name of readdirSync(packages)) {
    const bin = join(packages, name, "native", "bin");
    if (existsSync(join(bin, process.platform === "win32" ? "pg_ctl.exe" : "pg_ctl"))) return bin;
  }
  return null;
}

function pgCtl(bin, args, { quiet = false } = {}) {
  const exe = join(bin, process.platform === "win32" ? "pg_ctl.exe" : "pg_ctl");
  const res = spawnSync(exe, args, { encoding: "utf8" });
  if (res.status !== 0 && !quiet) {
    const detail = (res.stderr || res.stdout || "").trim();
    throw new Error(`pg_ctl ${args.join(" ")} failed${detail ? `: ${detail}` : ""}`);
  }
  return res;
}

async function loadEmbeddedPostgres() {
  try {
    const mod = await import("embedded-postgres");
    return mod.default ?? mod;
  } catch {
    warn(
      "embedded-postgres is not installed. Run `npm install` first, or install " +
        "PostgreSQL locally and set DATABASE_URL in .env.",
    );
    process.exit(1);
  }
}

async function initialiseCluster() {
  if (existsSync(join(DATA_DIR, "PG_VERSION"))) return false;
  const EmbeddedPostgres = await loadEmbeddedPostgres();
  mkdirSync(DATA_DIR, { recursive: true });
  mkdirSync(LOG_DIR, { recursive: true });
  log("initialising a project-local PostgreSQL cluster (.devdb/data)");
  const pg = new EmbeddedPostgres({
    databaseDir: DATA_DIR,
    user: USER,
    password: PASSWORD,
    port: DEFAULT_PORT,
    persistent: true,
    onLog: () => {},
  });
  await pg.initialise();
  return true;
}

/** Start the postmaster as a daemon: it must outlive this script. */
function startServer(bin, port) {
  mkdirSync(LOG_DIR, { recursive: true });
  pgCtl(bin, [
    "-D", DATA_DIR,
    "-l", LOG_FILE,
    "-o", `-p ${port} -c listen_addresses=127.0.0.1`,
    "-w",
    "-t", "60",
    "start",
  ]);
  log(`postgres listening on 127.0.0.1:${port} (log: .devdb/logs/postgres.log)`);
}

function stopServer(bin) {
  if (!existsSync(join(DATA_DIR, "postmaster.pid"))) return false;
  pgCtl(bin, ["-D", DATA_DIR, "-m", "fast", "-w", "-t", "30", "stop"], { quiet: true });
  return true;
}

// ────────────────────────────────────────────────────────────── database SQL

async function withClient(url, fn) {
  const { default: pg } = await import("pg");
  const client = new pg.Client({ connectionString: url });
  await client.connect();
  try {
    return await fn(client);
  } finally {
    await client.end();
  }
}

async function prepareDatabase(port) {
  const url = localUrl(port);
  await withClient(url, async (client) => {
    // French accent-insensitive search needs `unaccent`; fuzzy "did you mean"
    // needs `pg_trgm`. Both must exist before the first query runs.
    await client.query("CREATE EXTENSION IF NOT EXISTS unaccent");
    await client.query("CREATE EXTENSION IF NOT EXISTS pg_trgm");
    log("extensions ready: unaccent, pg_trgm");
  });
}

async function ensureDatabase(port) {
  // The cluster is created with the maintenance database `postgres`; the app
  // database is created here so `reset` behaves like a first install.
  const { default: pg } = await import("pg");
  const admin = new pg.Client({
    connectionString: `postgresql://${USER}:${PASSWORD}@127.0.0.1:${port}/postgres`,
  });
  await admin.connect();
  try {
    const { rowCount } = await admin.query("SELECT 1 FROM pg_database WHERE datname = $1", [DATABASE]);
    if (!rowCount) {
      await admin.query(`CREATE DATABASE "${DATABASE}"`);
      log(`created database "${DATABASE}"`);
    } else {
      log(`database "${DATABASE}" already exists — reusing`);
    }
  } finally {
    await admin.end();
  }
}

// ──────────────────────────────────────────────────────────────── commands

async function cmdStart() {
  const existing = databaseUrlFromEnv();
  const parsed = existing ? parseUrl(existing) : null;
  const state = readState();
  const bin = binDir();
  if (!bin) {
    warn("PostgreSQL binaries are missing. Run `npm install` to fetch embedded-postgres.");
    process.exit(1);
  }

  const port = state?.port ?? DEFAULT_PORT;
  const ownsThePort = state?.managed === true && Number(state?.port) === port;

  // A server the developer already runs: respect it, never touch it.
  if (parsed && !process.env.CLEOPATRE_FORCE_LOCAL_DB) {
    const isOurOwn =
      ownsThePort && parsed.host === "127.0.0.1" && parsed.port === port;
    if (!isOurOwn && (await isPortOpen(parsed.host, parsed.port))) {
      log(`using the PostgreSQL already available at ${parsed.host}:${parsed.port} (DATABASE_URL)`);
      await withClient(existing, async (client) => {
        try {
          await client.query("CREATE EXTENSION IF NOT EXISTS unaccent");
          await client.query("CREATE EXTENSION IF NOT EXISTS pg_trgm");
          log("extensions ready: unaccent, pg_trgm");
        } catch (error) {
          warn(`could not prepare extensions (${error.message}) — continuing`);
        }
      });
      return;
    }
  }

  const dataDirReady = existsSync(join(DATA_DIR, "PG_VERSION"));
  await initialiseCluster();

  if (await isPortOpen("127.0.0.1", port)) {
    // A port that answers is not proof that it is *our* cluster: if our data
    // directory was never created (or was deleted while a stray postmaster kept
    // running), the server on this port belongs to something else and would
    // serve the wrong database.
    if (!dataDirReady) {
      warn(
        `port ${port} is already in use by another process, so the project-local ` +
          `cluster cannot start there. Stop that process, or choose another port: ` +
          `DEV_DB_PORT=5435 node scripts/dev-db.mjs start`,
      );
      process.exit(1);
    }
    log(`project-local PostgreSQL already listening on ${port}`);
  } else {
    startServer(bin, port);
  }
  writeState({
    managed: true,
    port,
    database: DATABASE,
    user: USER,
    startedAt: new Date().toISOString(),
  });
  await ensureDatabase(port);
  await prepareDatabase(port);
  writeEnvDatabaseUrl(localUrl(port));
  log(`DATABASE_URL=${localUrl(port)}`);
}

async function cmdStop() {
  const state = readState();
  const bin = binDir();
  if (!bin) {
    log("nothing to stop");
    return;
  }
  const stopped = stopServer(bin);
  clearState();
  log(stopped ? "stopped" : state?.managed ? "was not running" : "no project-local cluster to stop");
}

async function cmdReset() {
  const bin = binDir();
  if (bin) stopServer(bin);
  rmSync(DATA_DIR, { recursive: true, force: true });
  clearState();
  log("local cluster removed");
  await cmdStart();
}

async function cmdStatus() {
  const state = readState();
  const bin = binDir();
  let running = false;
  if (bin && existsSync(join(DATA_DIR, "postmaster.pid"))) {
    const res = pgCtl(bin, ["-D", DATA_DIR, "status"], { quiet: true });
    running = res.status === 0;
  }
  const url = databaseUrlFromEnv() ?? localUrl(state?.port ?? DEFAULT_PORT);
  const parsed = parseUrl(url);
  const reachable = parsed ? await isPortOpen(parsed.host, parsed.port) : false;
  process.stdout.write(
    [
      `managed   : ${state?.managed ? `yes (project-local, .devdb/, port ${state.port})` : "no (using DATABASE_URL)"}`,
      `server    : ${running ? "running" : "stopped"}`,
      `reachable : ${reachable ? "yes" : "no"}`,
      `DATABASE_URL=${url}`,
      "",
    ].join("\n"),
  );
}

const command = process.argv[2] ?? "start";
const commands = { start: cmdStart, stop: cmdStop, reset: cmdReset, status: cmdStatus, url: cmdStatus };

if (!commands[command]) {
  warn(`unknown command "${command}" — use start | stop | reset | status | url`);
  process.exit(1);
}
try {
  await commands[command]();
} catch (error) {
  warn(error?.message ?? String(error));
  process.exit(1);
}
// The postmaster is daemonised by pg_ctl and outlives this process; exiting
// explicitly keeps `start` from hanging on the event loop.
process.exit(0);
